"""Authoritative project types, purpose subcategories and lifecycle stages.

Subcategory values are scoped to their parent category. Keep the readable
catalogue in FIRST/proje-kategorileri.md aligned when changing these constants.
Stages are owner-declared progress, not automated release or quality gates."""

CATEGORIES = [
    {
        "value": "web-app",
        "label": "Web Uygulaması",
        "subcategories": [
            {"value": "health", "label": "Sağlık ve Hasta Takibi"},
            {"value": "education", "label": "Eğitim ve Öğrenme"},
            {"value": "finance", "label": "Finans ve Bütçe"},
            {"value": "real-estate", "label": "Emlak ve Mülk Yönetimi"},
            {"value": "commerce", "label": "E-ticaret ve Mağazacılık"},
            {"value": "marketplace", "label": "Pazar Yeri ve Hizmet Eşleştirme"},
            {"value": "community", "label": "Topluluk ve Sosyal Ağ"},
            {"value": "collaboration", "label": "Ekip Çalışması ve Proje Yönetimi"},
            {"value": "productivity", "label": "Kişisel Üretkenlik"},
            {"value": "content-publishing", "label": "İçerik ve Yayıncılık"},
            {"value": "recruitment", "label": "İş ve Yetenek Eşleştirme"},
            {"value": "customer-relations", "label": "Müşteri İlişkileri"},
            {"value": "booking", "label": "Randevu ve Rezervasyon"},
            {"value": "events", "label": "Etkinlik ve Biletleme"},
            {"value": "travel", "label": "Seyahat ve Turizm"},
            {"value": "logistics", "label": "Lojistik ve Teslimat"},
            {"value": "food", "label": "Yemek ve Restoran Yönetimi"},
            {"value": "agriculture", "label": "Tarım ve Gıda Sistemleri"},
            {"value": "sustainability", "label": "Çevre ve Sürdürülebilirlik"},
            {"value": "civic-services", "label": "Kamusal Hizmetler ve Sivil Katılım"},
            {"value": "accessibility", "label": "Erişilebilirlik ve Kapsayıcılık"},
            {"value": "legal", "label": "Hukuk ve Uyum"},
            {"value": "security", "label": "Güvenlik ve Risk Yönetimi"},
            {"value": "entertainment", "label": "Medya ve Eğlence"},
            {"value": "other-web", "label": "Diğer Web Uygulamaları"},
        ],
    },
    {
        "value": "mobile-app",
        "label": "Mobil Uygulama",
        "subcategories": [
            {"value": "personal-health", "label": "Kişisel Sağlık Takibi"},
            {"value": "mental-wellbeing", "label": "Ruh Sağlığı ve İyi Oluş"},
            {"value": "fitness", "label": "Spor ve Egzersiz"},
            {"value": "nutrition", "label": "Beslenme ve Yemek Planlama"},
            {"value": "learning", "label": "Mobil Öğrenme"},
            {"value": "language-learning", "label": "Dil Öğrenme"},
            {"value": "personal-finance", "label": "Kişisel Finans"},
            {"value": "shopping", "label": "Alışveriş ve Sadakat"},
            {"value": "social", "label": "Sosyal İletişim ve Topluluk"},
            {"value": "local-discovery", "label": "Yerel Mekân ve Hizmet Keşfi"},
            {"value": "travel", "label": "Seyahat Planlama"},
            {"value": "navigation", "label": "Navigasyon ve Ulaşım"},
            {"value": "field-work", "label": "Saha Çalışması ve Ekip Yönetimi"},
            {"value": "home-management", "label": "Ev ve Yaşam Yönetimi"},
            {"value": "caregiving", "label": "Aile ve Bakım Desteği"},
            {"value": "accessibility", "label": "Erişilebilirlik Desteği"},
            {"value": "personal-safety", "label": "Kişisel Güvenlik ve Acil Durum"},
            {"value": "habits", "label": "Alışkanlık ve Günlük Planlama"},
            {"value": "creativity", "label": "Fotoğraf, Ses ve Yaratıcı Üretim"},
            {"value": "events", "label": "Etkinlik ve Sosyal Buluşma"},
            {"value": "agriculture", "label": "Çiftçi ve Tarla Desteği"},
            {"value": "property", "label": "Emlak Arama ve Mülk Takibi"},
            {"value": "other-mobile", "label": "Diğer Mobil Uygulamalar"},
        ],
    },
    {
        "value": "desktop-app",
        "label": "Masaüstü Uygulaması",
        "subcategories": [
            {"value": "document-work", "label": "Belge ve Ofis Çalışması"},
            {"value": "creative-design", "label": "Görsel Tasarım ve İllüstrasyon"},
            {"value": "video-production", "label": "Video Üretimi ve Kurgu"},
            {"value": "audio-production", "label": "Ses ve Müzik Üretimi"},
            {"value": "engineering-design", "label": "Mühendislik ve Teknik Çizim"},
            {"value": "research-analysis", "label": "Araştırma ve Veri Analizi"},
            {"value": "software-work", "label": "Yazılım Geliştirme Desteği"},
            {"value": "file-management", "label": "Dosya ve Arşiv Yönetimi"},
            {"value": "knowledge-management", "label": "Not ve Bilgi Yönetimi"},
            {"value": "communication", "label": "İletişim ve Toplantı"},
            {"value": "business-operations", "label": "İşletme Operasyonları"},
            {"value": "accessibility", "label": "Masaüstü Erişilebilirliği"},
            {"value": "privacy-security", "label": "Gizlilik ve Cihaz Güvenliği"},
            {"value": "education", "label": "Eğitim ve Sınıf Çalışması"},
            {"value": "other-desktop", "label": "Diğer Masaüstü Uygulamaları"},
        ],
    },
    {
        "value": "ai-agent",
        "label": "Yapay Zekâ Ajanı",
        "subcategories": [
            {"value": "research", "label": "Araştırma ve Kaynak Tarama"},
            {"value": "coding", "label": "Kod Geliştirme ve Bakım"},
            {"value": "software-quality", "label": "Yazılım İnceleme ve Kalite"},
            {"value": "cyber-defense", "label": "Siber Savunma ve Olay Analizi"},
            {"value": "customer-support", "label": "Müşteri Destek Operasyonları"},
            {"value": "sales", "label": "Satış ve Müşteri Takibi"},
            {"value": "marketing", "label": "Pazarlama ve Kampanya Yönetimi"},
            {"value": "content-operations", "label": "İçerik Üretimi ve Yayın Akışı"},
            {"value": "personal-assistant", "label": "Kişisel Asistanlık ve Planlama"},
            {"value": "learning-coach", "label": "Öğrenme ve Eğitim Koçluğu"},
            {"value": "health-support", "label": "Sağlık Bilgilendirme ve Bakım Desteği"},
            {"value": "finance-analysis", "label": "Finansal Araştırma ve Analiz"},
            {"value": "legal-research", "label": "Hukuki Araştırma ve Belge İnceleme"},
            {"value": "real-estate", "label": "Emlak Araştırma ve Eşleştirme"},
            {"value": "recruitment", "label": "İşe Alım ve Aday Eşleştirme"},
            {"value": "project-coordination", "label": "Proje ve Ekip Koordinasyonu"},
            {"value": "business-operations", "label": "İş Süreci Operasyonları"},
            {"value": "data-analysis", "label": "Veri Analizi ve Raporlama"},
            {"value": "it-operations", "label": "BT Operasyonları ve Sorun Giderme"},
            {"value": "commerce", "label": "Alışveriş ve Ticaret Desteği"},
            {"value": "travel-planning", "label": "Seyahat ve Rezervasyon Planlama"},
            {"value": "accessibility", "label": "Erişilebilirlik ve Günlük Yaşam Desteği"},
            {"value": "scientific-discovery", "label": "Bilimsel Araştırma Desteği"},
            {"value": "other-agent", "label": "Diğer Yapay Zekâ Ajanları"},
        ],
    },
    {
        "value": "ai-model",
        "label": "Yapay Zekâ Modeli",
        "subcategories": [
            {"value": "health", "label": "Sağlık Araştırması ve Klinik Destek"},
            {"value": "biomedicine", "label": "Biyomedikal ve İlaç Araştırması"},
            {"value": "cybersecurity", "label": "Siber Tehdit ve Anomali Tespiti"},
            {"value": "fraud-detection", "label": "Dolandırıcılık ve Kötüye Kullanım Tespiti"},
            {"value": "financial-risk", "label": "Finansal Risk ve Öngörü"},
            {"value": "language-access", "label": "Çeviri ve Dil Erişimi"},
            {"value": "accessibility", "label": "Engelsiz İletişim ve Erişilebilirlik"},
            {"value": "education", "label": "Öğrenme ve Eğitim Değerlendirmesi"},
            {"value": "scientific-research", "label": "Bilimsel Keşif ve Araştırma"},
            {"value": "climate", "label": "İklim ve Çevre Analizi"},
            {"value": "agriculture", "label": "Tarım ve Bitki Sağlığı"},
            {"value": "industrial-quality", "label": "Üretim Kalitesi ve Hata Tespiti"},
            {"value": "predictive-maintenance", "label": "Arıza Öngörüsü ve Bakım"},
            {"value": "transport", "label": "Trafik ve Ulaşım Analizi"},
            {"value": "energy", "label": "Enerji Talebi ve Verimlilik"},
            {"value": "real-estate", "label": "Gayrimenkul Değerleme ve Analizi"},
            {"value": "commerce", "label": "Talep Tahmini ve Ticaret Analizi"},
            {"value": "recommendations", "label": "İçerik ve Ürün Önerileri"},
            {"value": "content-safety", "label": "İçerik Güvenliği ve Moderasyon"},
            {"value": "creative-production", "label": "Yaratıcı İçerik Üretimi"},
            {"value": "software-assistance", "label": "Kodlama ve Yazılım Anlama"},
            {"value": "search-knowledge", "label": "Bilgi Arama ve Anlamlandırma"},
            {"value": "other-model", "label": "Diğer Yapay Zekâ Modelleri"},
        ],
    },
    {
        "value": "ai-tool",
        "label": "Yapay Zekâ Destekli Araç",
        "subcategories": [
            {"value": "writing", "label": "Yazı ve Editörlük"},
            {"value": "visual-creation", "label": "Görsel Üretim ve Düzenleme"},
            {"value": "video-creation", "label": "Video Üretimi ve Düzenleme"},
            {"value": "audio-creation", "label": "Ses ve Müzik Çalışmaları"},
            {"value": "meeting-assistance", "label": "Toplantı ve Görüşme Desteği"},
            {"value": "translation", "label": "Çeviri ve Yerelleştirme"},
            {"value": "coding-assistance", "label": "Kodlama ve Hata Giderme"},
            {"value": "research-assistance", "label": "Araştırma ve Kaynak Değerlendirme"},
            {"value": "document-analysis", "label": "Belge Okuma ve Bilgi Çıkarma"},
            {"value": "data-insights", "label": "Veri Analizi ve İçgörü"},
            {"value": "learning-assistance", "label": "Ders Çalışma ve Öğrenme"},
            {"value": "accessibility", "label": "Erişilebilir İçerik ve İletişim"},
            {"value": "health-information", "label": "Sağlık Bilgilendirme"},
            {"value": "legal-assistance", "label": "Hukuki Belge ve Araştırma Desteği"},
            {"value": "finance-assistance", "label": "Finansal Analiz Desteği"},
            {"value": "real-estate", "label": "Emlak İnceleme ve Sunum"},
            {"value": "marketing-assistance", "label": "Pazarlama ve Marka İçeriği"},
            {"value": "security-assistance", "label": "Güvenlik Analizi Desteği"},
            {"value": "career-assistance", "label": "Kariyer ve Başvuru Desteği"},
            {"value": "other-ai-tool", "label": "Diğer Yapay Zekâ Araçları"},
        ],
    },
    {
        "value": "backend-system",
        "label": "Backend Sistemi",
        "subcategories": [
            {"value": "identity-access", "label": "Kimlik ve Erişim Yönetimi"},
            {"value": "commerce-operations", "label": "Sipariş ve Ticaret Operasyonları"},
            {"value": "payments-billing", "label": "Ödeme ve Faturalandırma"},
            {"value": "inventory", "label": "Stok ve Tedarik Yönetimi"},
            {"value": "logistics", "label": "Lojistik ve Sevkiyat Yönetimi"},
            {"value": "booking", "label": "Randevu ve Rezervasyon Yönetimi"},
            {"value": "communication", "label": "Mesajlaşma ve Bildirim"},
            {"value": "content-management", "label": "İçerik ve Medya Yönetimi"},
            {"value": "community-management", "label": "Topluluk ve Üyelik Yönetimi"},
            {"value": "learning-management", "label": "Eğitim ve Öğrenme Yönetimi"},
            {"value": "health-records", "label": "Sağlık ve Bakım Kayıtları"},
            {"value": "financial-records", "label": "Finans ve Muhasebe Kayıtları"},
            {"value": "property-management", "label": "Mülk ve Kiralama Yönetimi"},
            {"value": "workflow-management", "label": "İş Akışı ve Süreç Yönetimi"},
            {"value": "compliance-audit", "label": "Uyum ve Denetim Kayıtları"},
            {"value": "public-services", "label": "Kamu ve Belediye Hizmetleri"},
            {"value": "other-backend", "label": "Diğer Backend Sistemleri"},
        ],
    },
    {
        "value": "api-service",
        "label": "API Servisi",
        "subcategories": [
            {"value": "identity-verification", "label": "Kimlik ve Hesap Doğrulama"},
            {"value": "payments", "label": "Ödeme ve Finans İşlemleri"},
            {"value": "messaging", "label": "Mesaj ve Bildirim İletimi"},
            {"value": "maps-location", "label": "Harita ve Konum Hizmetleri"},
            {"value": "weather-climate", "label": "Hava Durumu ve İklim Verileri"},
            {"value": "transport-logistics", "label": "Ulaşım ve Lojistik Verileri"},
            {"value": "health-data", "label": "Sağlık Verisi Entegrasyonu"},
            {"value": "education-data", "label": "Eğitim Verisi Entegrasyonu"},
            {"value": "commerce-data", "label": "Ürün, Fiyat ve Stok Verileri"},
            {"value": "property-data", "label": "Emlak ve Adres Verileri"},
            {"value": "public-data", "label": "Açık Veri ve Kamusal Veriler"},
            {"value": "search-discovery", "label": "Arama ve Bilgi Keşfi"},
            {"value": "media-processing", "label": "Medya İşleme ve Dağıtımı"},
            {"value": "language-services", "label": "Dil ve Çeviri Hizmetleri"},
            {"value": "risk-intelligence", "label": "Güvenlik ve Risk İstihbaratı"},
            {"value": "other-api", "label": "Diğer API Servisleri"},
        ],
    },
    {
        "value": "library-sdk",
        "label": "Kütüphane ve SDK",
        "subcategories": [
            {"value": "identity-security", "label": "Kimlik ve Güvenlik Entegrasyonu"},
            {"value": "payment-integration", "label": "Ödeme ve Ticaret Entegrasyonu"},
            {"value": "data-processing", "label": "Veri İşleme ve Dönüştürme"},
            {"value": "data-visualization", "label": "Veri Görselleştirme"},
            {"value": "scientific-analysis", "label": "Bilimsel ve Sayısal Analiz"},
            {"value": "media-processing", "label": "Görüntü, Ses ve Video İşleme"},
            {"value": "language-processing", "label": "Dil ve Metin İşleme"},
            {"value": "accessibility", "label": "Erişilebilirlik Geliştirme"},
            {"value": "localization", "label": "Çeviri ve Yerelleştirme"},
            {"value": "maps-geospatial", "label": "Harita ve Coğrafi Analiz"},
            {"value": "developer-productivity", "label": "Geliştirici Üretkenliği"},
            {"value": "quality-assurance", "label": "Yazılım Kalitesi ve Doğrulama"},
            {"value": "observability", "label": "Sistem İzleme ve Hata Analizi"},
            {"value": "device-integration", "label": "Cihaz ve Donanım Entegrasyonu"},
            {"value": "other-library", "label": "Diğer Kütüphane ve SDK'lar"},
        ],
    },
    {
        "value": "cli-tool",
        "label": "Komut Satırı Aracı",
        "subcategories": [
            {"value": "project-setup", "label": "Proje Kurulumu ve İskelet Oluşturma"},
            {"value": "code-maintenance", "label": "Kod Düzenleme ve Bakım"},
            {"value": "release-management", "label": "Sürüm ve Yayın Yönetimi"},
            {"value": "infrastructure-management", "label": "Altyapı ve Ortam Yönetimi"},
            {"value": "data-conversion", "label": "Veri Dönüştürme ve Aktarma"},
            {"value": "database-operations", "label": "Veritabanı Yönetimi"},
            {"value": "file-operations", "label": "Dosya ve Arşiv İşlemleri"},
            {"value": "backup-recovery", "label": "Yedekleme ve Kurtarma"},
            {"value": "security-audit", "label": "Güvenlik Denetimi"},
            {"value": "network-diagnostics", "label": "Ağ Analizi ve Sorun Giderme"},
            {"value": "media-operations", "label": "Medya İşleme"},
            {"value": "research-workflows", "label": "Araştırma İş Akışları"},
            {"value": "personal-productivity", "label": "Kişisel Üretkenlik"},
            {"value": "other-cli", "label": "Diğer Komut Satırı Araçları"},
        ],
    },
    {
        "value": "browser-extension",
        "label": "Tarayıcı Eklentisi",
        "subcategories": [
            {"value": "privacy-protection", "label": "Gizlilik ve Takip Koruması"},
            {"value": "browsing-security", "label": "Güvenli Gezinme"},
            {"value": "accessibility", "label": "Web Erişilebilirliği"},
            {"value": "reading-research", "label": "Okuma ve Araştırma"},
            {"value": "translation", "label": "Çeviri ve Dil Desteği"},
            {"value": "writing-assistance", "label": "Yazma ve Metin Desteği"},
            {"value": "productivity-focus", "label": "Üretkenlik ve Odaklanma"},
            {"value": "bookmark-knowledge", "label": "Yer İmi ve Bilgi Yönetimi"},
            {"value": "shopping-comparison", "label": "Alışveriş ve Fiyat Karşılaştırma"},
            {"value": "web-development", "label": "Web Geliştirme ve İnceleme"},
            {"value": "content-management", "label": "İçerik Kaydetme ve Düzenleme"},
            {"value": "learning", "label": "Öğrenme ve Ders Çalışma"},
            {"value": "other-extension", "label": "Diğer Tarayıcı Eklentileri"},
        ],
    },
    {
        "value": "automation-workflow",
        "label": "Otomasyon ve İş Akışı",
        "subcategories": [
            {"value": "sales-operations", "label": "Satış ve Müşteri Operasyonları"},
            {"value": "marketing-operations", "label": "Pazarlama ve Kampanya Akışları"},
            {"value": "support-operations", "label": "Müşteri Destek Akışları"},
            {"value": "finance-operations", "label": "Finans ve Muhasebe Akışları"},
            {"value": "hr-operations", "label": "İnsan Kaynakları ve İşe Alım"},
            {"value": "commerce-operations", "label": "Ticaret ve Sipariş Akışları"},
            {"value": "content-publishing", "label": "İçerik Hazırlama ve Yayınlama"},
            {"value": "document-processing", "label": "Belge İşleme ve Onay"},
            {"value": "research-collection", "label": "Araştırma ve Bilgi Toplama"},
            {"value": "data-synchronization", "label": "Veri Aktarımı ve Eşitleme"},
            {"value": "it-maintenance", "label": "BT Bakım ve Operasyonları"},
            {"value": "security-response", "label": "Güvenlik Uyarısı ve Müdahale"},
            {"value": "personal-productivity", "label": "Kişisel Görev ve Hatırlatmalar"},
            {"value": "community-operations", "label": "Topluluk ve Etkinlik Operasyonları"},
            {"value": "other-automation", "label": "Diğer Otomasyon Akışları"},
        ],
    },
    {
        "value": "data-platform",
        "label": "Veri Platformu",
        "subcategories": [
            {"value": "public-data", "label": "Açık Veri ve Kamusal Bilgi"},
            {"value": "health-research", "label": "Sağlık ve Klinik Araştırma Verileri"},
            {"value": "finance-analytics", "label": "Finans ve Ekonomi Analitiği"},
            {"value": "commerce-analytics", "label": "Ticaret ve Müşteri Analitiği"},
            {"value": "education-analytics", "label": "Eğitim ve Öğrenme Analitiği"},
            {"value": "climate-environment", "label": "İklim ve Çevre Verileri"},
            {"value": "agriculture-food", "label": "Tarım ve Gıda Verileri"},
            {"value": "geospatial", "label": "Coğrafi Bilgi ve Kent Analitiği"},
            {"value": "transport-logistics", "label": "Ulaşım ve Lojistik Analitiği"},
            {"value": "industrial-analytics", "label": "Üretim ve Bakım Analitiği"},
            {"value": "energy-analytics", "label": "Enerji ve Kaynak Analitiği"},
            {"value": "security-analytics", "label": "Güvenlik ve Tehdit Verileri"},
            {"value": "research-data", "label": "Bilimsel Veri Paylaşımı"},
            {"value": "organizational-knowledge", "label": "Kurumsal Bilgi ve Veri Yönetimi"},
            {"value": "other-data", "label": "Diğer Veri Platformları"},
        ],
    },
    {
        "value": "devops-platform",
        "label": "DevOps ve Altyapı Platformu",
        "subcategories": [
            {"value": "release-delivery", "label": "Yazılım Yayınlama ve Teslim"},
            {"value": "environment-management", "label": "Geliştirme ve Çalışma Ortamları"},
            {"value": "infrastructure-provisioning", "label": "Altyapı Kurulumu ve Yönetimi"},
            {"value": "service-reliability", "label": "Hizmet Sürekliliği ve Güvenilirlik"},
            {"value": "system-observability", "label": "Sistem Gözlemi ve Sorun Analizi"},
            {"value": "incident-management", "label": "Operasyonel Olay Yönetimi"},
            {"value": "cloud-cost", "label": "Bulut Maliyeti ve Kaynak Verimliliği"},
            {"value": "backup-recovery", "label": "Yedekleme ve Felaket Kurtarma"},
            {"value": "secrets-access", "label": "Gizli Bilgi ve Altyapı Erişimi"},
            {"value": "supply-chain-security", "label": "Yazılım Tedarik Zinciri Güvenliği"},
            {"value": "compliance-reporting", "label": "Altyapı Uyumu ve Denetim"},
            {"value": "team-self-service", "label": "Geliştirici Platformu ve Self Servis"},
            {"value": "other-devops", "label": "Diğer DevOps Platformları"},
        ],
    },
    {
        "value": "cybersecurity-tool",
        "label": "Siber Güvenlik Aracı",
        "subcategories": [
            {"value": "application-security", "label": "Uygulama Güvenliği"},
            {"value": "network-defense", "label": "Ağ Güvenliği ve Savunması"},
            {"value": "endpoint-protection", "label": "Cihaz ve Uç Nokta Koruması"},
            {"value": "cloud-security", "label": "Bulut Güvenliği"},
            {"value": "identity-security", "label": "Kimlik ve Erişim Güvenliği"},
            {"value": "vulnerability-management", "label": "Zafiyet Yönetimi"},
            {"value": "threat-intelligence", "label": "Tehdit İstihbaratı"},
            {"value": "incident-response", "label": "Olay Müdahalesi"},
            {"value": "forensics", "label": "Dijital Adli Analiz"},
            {"value": "phishing-defense", "label": "Kimlik Avı ve Dolandırıcılık Koruması"},
            {"value": "data-protection", "label": "Veri Güvenliği ve Gizlilik"},
            {"value": "security-awareness", "label": "Güvenlik Eğitimi ve Farkındalık"},
            {"value": "security-validation", "label": "Yetkili Güvenlik Değerlendirmesi"},
            {"value": "compliance-risk", "label": "Güvenlik Uyumu ve Risk Yönetimi"},
            {"value": "other-security", "label": "Diğer Siber Güvenlik Araçları"},
        ],
    },
    {
        "value": "iot-system",
        "label": "Nesnelerin İnterneti Sistemi",
        "subcategories": [
            {"value": "smart-home", "label": "Akıllı Ev ve Yaşam Alanları"},
            {"value": "smart-building", "label": "Bina ve Tesis Yönetimi"},
            {"value": "health-monitoring", "label": "Uzaktan Sağlık ve Bakım Takibi"},
            {"value": "agriculture-monitoring", "label": "Tarım ve Sulama Takibi"},
            {"value": "industrial-monitoring", "label": "Üretim ve Makine İzleme"},
            {"value": "energy-management", "label": "Enerji ve Tüketim Yönetimi"},
            {"value": "environment-monitoring", "label": "Hava, Su ve Çevre İzleme"},
            {"value": "asset-tracking", "label": "Varlık ve Envanter Takibi"},
            {"value": "transport-fleet", "label": "Ulaşım ve Filo Takibi"},
            {"value": "cold-chain", "label": "Soğuk Zincir ve Gıda Güvenliği"},
            {"value": "urban-services", "label": "Kent Altyapısı ve Hizmetleri"},
            {"value": "disaster-monitoring", "label": "Afet ve Erken Uyarı"},
            {"value": "other-iot", "label": "Diğer IoT Sistemleri"},
        ],
    },
    {
        "value": "embedded-system",
        "label": "Gömülü Sistem",
        "subcategories": [
            {"value": "medical-devices", "label": "Sağlık ve Yardımcı Cihazlar"},
            {"value": "assistive-devices", "label": "Erişilebilirlik ve Destek Cihazları"},
            {"value": "industrial-control", "label": "Endüstriyel Kontrol"},
            {"value": "vehicle-systems", "label": "Araç ve Ulaşım Sistemleri"},
            {"value": "energy-control", "label": "Enerji ve Güç Yönetimi"},
            {"value": "consumer-devices", "label": "Günlük Yaşam ve Tüketici Cihazları"},
            {"value": "measurement", "label": "Ölçüm ve Veri Toplama"},
            {"value": "communication-devices", "label": "Haberleşme Cihazları"},
            {"value": "agriculture-control", "label": "Tarım ve Sulama Kontrolü"},
            {"value": "safety-systems", "label": "Emniyet ve Alarm Sistemleri"},
            {"value": "education-kits", "label": "Eğitim ve Deney Setleri"},
            {"value": "other-embedded", "label": "Diğer Gömülü Sistemler"},
        ],
    },
    {
        "value": "robotics",
        "label": "Robotik",
        "subcategories": [
            {"value": "industrial-production", "label": "Üretim ve Montaj"},
            {"value": "warehouse-logistics", "label": "Depo ve Lojistik"},
            {"value": "health-rehabilitation", "label": "Sağlık ve Rehabilitasyon"},
            {"value": "assistive-care", "label": "Bakım ve Günlük Yaşam Desteği"},
            {"value": "agriculture", "label": "Tarım ve Hasat"},
            {"value": "inspection-maintenance", "label": "İnceleme ve Bakım"},
            {"value": "search-rescue", "label": "Arama ve Kurtarma"},
            {"value": "education", "label": "Robotik Eğitimi"},
            {"value": "research-exploration", "label": "Araştırma ve Keşif"},
            {"value": "home-services", "label": "Ev ve Tesis Hizmetleri"},
            {"value": "environment-restoration", "label": "Çevre İzleme ve İyileştirme"},
            {"value": "other-robotics", "label": "Diğer Robotik Projeleri"},
        ],
    },
    {
        "value": "game",
        "label": "Oyun",
        "subcategories": [
            {"value": "entertainment", "label": "Eğlence ve Serbest Oyun"},
            {"value": "education", "label": "Eğitim ve Kavram Öğrenme"},
            {"value": "language-learning", "label": "Dil Öğrenme ve Pratik"},
            {"value": "health-rehabilitation", "label": "Sağlık ve Rehabilitasyon"},
            {"value": "cognitive-training", "label": "Bilişsel Beceri ve Hafıza"},
            {"value": "professional-training", "label": "Mesleki Eğitim ve Simülasyon"},
            {"value": "social-cooperation", "label": "Sosyal Etkileşim ve İş Birliği"},
            {"value": "culture-history", "label": "Kültür, Tarih ve Miras"},
            {"value": "science-exploration", "label": "Bilim ve Keşif"},
            {"value": "civic-awareness", "label": "Toplumsal Farkındalık"},
            {"value": "accessibility", "label": "Erişilebilir Oyun Deneyimi"},
            {"value": "creative-expression", "label": "Yaratıcılık ve Anlatı"},
            {"value": "other-game", "label": "Diğer Oyun Amaçları"},
        ],
    },
    {
        "value": "xr-app",
        "label": "XR / AR / VR Uygulaması",
        "subcategories": [
            {"value": "immersive-learning", "label": "Deneyimsel Eğitim"},
            {"value": "professional-training", "label": "Mesleki Eğitim ve Güvenlik"},
            {"value": "health-rehabilitation", "label": "Sağlık ve Rehabilitasyon"},
            {"value": "architecture-property", "label": "Mimari ve Emlak Deneyimi"},
            {"value": "industrial-assistance", "label": "Üretim ve Bakım Desteği"},
            {"value": "remote-collaboration", "label": "Uzaktan İş Birliği"},
            {"value": "culture-heritage", "label": "Kültür ve Miras Keşfi"},
            {"value": "retail-experience", "label": "Alışveriş ve Ürün Deneyimi"},
            {"value": "entertainment", "label": "Eğlence ve Etkileşimli Deneyim"},
            {"value": "scientific-visualization", "label": "Bilimsel Görselleştirme"},
            {"value": "accessibility", "label": "Erişilebilirlik ve Yardımcı Deneyimler"},
            {"value": "tourism", "label": "Seyahat ve Mekân Keşfi"},
            {"value": "other-xr", "label": "Diğer XR Uygulamaları"},
        ],
    },
    {
        "value": "blockchain-app",
        "label": "Blokzincir Uygulaması",
        "subcategories": [
            {"value": "identity-credentials", "label": "Kimlik ve Doğrulanabilir Belgeler"},
            {"value": "payment-transfer", "label": "Ödeme ve Değer Transferi"},
            {"value": "financial-services", "label": "Finansal Hizmetler"},
            {"value": "supply-chain", "label": "Tedarik Zinciri ve İzlenebilirlik"},
            {"value": "ownership-rights", "label": "Mülkiyet ve Hak Yönetimi"},
            {"value": "community-governance", "label": "Topluluk Yönetimi ve Katılım"},
            {"value": "public-transparency", "label": "Kamusal Şeffaflık ve Hesap Verebilirlik"},
            {"value": "creator-economy", "label": "Üretici ve İçerik Ekonomisi"},
            {"value": "research-integrity", "label": "Araştırma Kaydı ve Bütünlüğü"},
            {"value": "environment-markets", "label": "Çevre ve Kaynak Takibi"},
            {"value": "charity-funding", "label": "Bağış ve Topluluk Finansmanı"},
            {"value": "other-blockchain", "label": "Diğer Blokzincir Uygulamaları"},
        ],
    },
    {
        "value": "scientific-computing",
        "label": "Bilimsel Hesaplama",
        "subcategories": [
            {"value": "bioinformatics", "label": "Biyoinformatik ve Genom Araştırması"},
            {"value": "drug-discovery", "label": "İlaç ve Molekül Araştırması"},
            {"value": "physics", "label": "Fizik ve Evren Araştırması"},
            {"value": "chemistry", "label": "Kimya ve Malzeme Araştırması"},
            {"value": "climate-modeling", "label": "İklim ve Meteoroloji"},
            {"value": "geoscience", "label": "Yer Bilimleri ve Afet Analizi"},
            {"value": "engineering-simulation", "label": "Mühendislik Tasarımı ve Simülasyon"},
            {"value": "energy-research", "label": "Enerji Sistemleri Araştırması"},
            {"value": "math-research", "label": "Matematik ve İstatistik Araştırması"},
            {"value": "social-research", "label": "Sosyal Bilimler ve Ekonomi"},
            {"value": "neuroscience", "label": "Sinirbilim ve Biliş Araştırması"},
            {"value": "ecology", "label": "Ekoloji ve Biyoçeşitlilik"},
            {"value": "other-scientific", "label": "Diğer Bilimsel Hesaplama Projeleri"},
        ],
    },
    {
        "value": "skill-files",
        "label": "Skill Dosyaları ve Ajan Talimatları",
        "subcategories": [
            {"value": "software-development", "label": "Yazılım Geliştirme"},
            {"value": "code-review", "label": "Kod İnceleme ve Kalite"},
            {"value": "security-review", "label": "Güvenlik İncelemesi"},
            {"value": "infrastructure-operations", "label": "Altyapı ve Yayın Operasyonları"},
            {"value": "research-synthesis", "label": "Araştırma ve Bilgi Sentezi"},
            {"value": "data-analysis", "label": "Veri Analizi ve Raporlama"},
            {"value": "writing-editing", "label": "Yazı ve Editörlük"},
            {"value": "product-design", "label": "Ürün ve Deneyim Tasarımı"},
            {"value": "marketing-content", "label": "Pazarlama ve Marka İçeriği"},
            {"value": "education-coaching", "label": "Eğitim ve Öğrenme Desteği"},
            {"value": "document-production", "label": "Belge ve Sunum Hazırlama"},
            {"value": "project-management", "label": "Proje ve Görev Yönetimi"},
            {"value": "customer-support", "label": "Müşteri Destek Süreçleri"},
            {"value": "legal-compliance", "label": "Hukuki Araştırma ve Uyum"},
            {"value": "accessibility-review", "label": "Erişilebilirlik İncelemesi"},
            {"value": "other-skills", "label": "Diğer Skill Dosyaları"},
        ],
    },
    {
        "value": "documentation",
        "label": "Dokümantasyon ve Bilgi Kaynağı",
        "subcategories": [
            {"value": "getting-started", "label": "Başlangıç ve Kullanım Rehberleri"},
            {"value": "developer-integration", "label": "Geliştirici ve Entegrasyon Rehberleri"},
            {"value": "architecture-decisions", "label": "Mimari ve Karar Kayıtları"},
            {"value": "operations-runbooks", "label": "İşletim ve Sorun Giderme Rehberleri"},
            {"value": "security-guidance", "label": "Güvenlik ve Gizlilik Rehberleri"},
            {"value": "contribution-governance", "label": "Katkı ve Topluluk Rehberleri"},
            {"value": "learning-materials", "label": "Eğitim ve Öğrenme Kaynakları"},
            {"value": "research-methods", "label": "Araştırma ve Yöntem Belgeleri"},
            {"value": "data-reference", "label": "Veri Sözlükleri ve Başvuru Kaynakları"},
            {"value": "accessibility-guidance", "label": "Erişilebilirlik Rehberleri"},
            {"value": "localization-guidance", "label": "Çeviri ve Yerelleştirme Kaynakları"},
            {"value": "compliance-guidance", "label": "Standart ve Uyum Rehberleri"},
            {"value": "product-knowledge", "label": "Ürün ve Alan Bilgisi"},
            {"value": "other-documentation", "label": "Diğer Dokümantasyon Kaynakları"},
        ],
    },
    {
        "value": "ui-component-system",
        "label": "UI Bileşen ve Tasarım Sistemi",
        "subcategories": [
            {"value": "accessible-interfaces", "label": "Erişilebilir Arayüzler"},
            {"value": "business-workflows", "label": "İşletme ve Yönetim Arayüzleri"},
            {"value": "commerce-experience", "label": "Alışveriş ve Ticaret Arayüzleri"},
            {"value": "learning-experience", "label": "Eğitim ve Öğrenme Arayüzleri"},
            {"value": "health-experience", "label": "Sağlık ve Bakım Arayüzleri"},
            {"value": "finance-experience", "label": "Finans ve Analiz Arayüzleri"},
            {"value": "data-exploration", "label": "Veri Keşfi ve Görselleştirme"},
            {"value": "content-experience", "label": "İçerik ve Yayın Arayüzleri"},
            {"value": "community-experience", "label": "Topluluk ve İletişim Arayüzleri"},
            {"value": "maps-navigation", "label": "Harita ve Konum Arayüzleri"},
            {"value": "public-services", "label": "Kamusal Hizmet Arayüzleri"},
            {"value": "cross-product-consistency", "label": "Ürünler Arası Görsel Tutarlılık"},
            {"value": "other-ui-system", "label": "Diğer UI Bileşen Sistemleri"},
        ],
    },
]

STAGES = [
    {
        "value": "idea",
        "label": "Fikir ve Planlama",
        "description": "Amaç, kapsam ve ihtiyaçlar netleştiriliyor; uygulama henüz başlamamış olabilir.",
    },
    {
        "value": "prototype",
        "label": "İlk Prototip",
        "description": "İlk çalışan örnek veya başlangıç çıktıları hazırlanıyor; temel yaklaşım deneniyor.",
    },
    {
        "value": "development",
        "label": "Aktif Geliştirme",
        "description": "Temel özellikler ve içerikler geliştiriliyor; proje kapsamı adım adım tamamlanıyor.",
    },
    {
        "value": "release-preparation",
        "label": "Yayına Hazırlık",
        "description": "İlk yayının kapsamı toparlanıyor; dağıtım, kullanım ve sunum hazırlıkları yapılıyor.",
    },
    {
        "value": "pre-release-testing",
        "label": "Yayın Öncesi Test",
        "description": "Yayın adayı son kontrollerden geçiyor; hatalar ve eksikler gideriliyor.",
    },
    {
        "value": "live-development",
        "label": "Yayında ve Geliştiriliyor",
        "description": "Proje kullanıma veya erişime açıldı; iyileştirme ve yeni özellik çalışmaları sürüyor.",
    },
]
