import {render,screen,fireEvent,waitFor} from '@testing-library/react';
import {beforeEach,expect,it,vi} from 'vitest';
import {api} from '../src/lib/api';
import {MyProjects,ProjectDetail,ProjectEditor} from '../src/components/projects';
import type {ReactNode} from 'react';
const state=vi.hoisted(()=>({user:{id:1,email_verified:true,providers:['github']} as {id:number;email_verified:boolean;providers:string[]}|null,push:vi.fn()}));
vi.mock('next/navigation',()=>({useRouter:()=>({push:state.push})}));
vi.mock('../src/lib/api',async original=>({...await original<typeof import('../src/lib/api')>(),api:vi.fn()}));
vi.mock('../src/components/session-provider',()=>({useSession:()=>({user:state.user,status:'ready'}),RequireSession:({children}:{children:ReactNode})=>state.user?children:<a href="/giris">Giriş yap</a>,SessionPending:()=>null}));
const project={id:'123',title:'Örnek proje',category:'software',subcategory:'web',stage:'idea',description:'Açıklama',readme_excerpt:'Kısa özet.',is_private:true,repository_url:'https://github.com/owner/secret',repository_name:'owner/secret',is_active:true,created_at:'',updated_at:'',need_type:'contributor',participation_mode:'application',visibility:'public',applications_open:true,current_state:'',desired_outcome:'',is_owner:false,can_apply:true};
const repo={id:1,installation_id:2,full_name:'owner/secret',name:'secret',private:true,description:'',html_url:'https://github.com/owner/secret'};
const config={categories:[{value:'software',label:'Yazılım',subcategories:[{value:'web',label:'Web'}]}],stages:[{value:'idea',label:'Fikir'}],github_app_enabled:true,need_types:[{value:'contributor',label:'Contributor'},{value:'feature',label:'Özellik'},{value:'bug',label:'Hata'}],participation_modes:[{value:'application',label:'Başvuru'},{value:'automatic',label:'Otomatik'},{value:'pr',label:'PR'}],visibilities:[{value:'public',label:'Herkese açık'},{value:'link',label:'Bağlantı'},{value:'selected',label:'Seçilen kişiler'}]};
beforeEach(()=>{vi.mocked(api).mockReset();state.push.mockReset();state.user={id:1,email_verified:true,providers:['github']};});
function editorApi(privateRepo=true){const chosen={...repo,private:privateRepo};vi.mocked(api).mockImplementation(async(path)=>{if(path==='projects/config')return config;if(path==='projects/mine')return {projects:[project]};if(path==='projects/github/status')return {enabled:true,connected:true};if(path==='projects/github/repositories')return {repositories:[chosen]};if(path==='projects/github/preview')return {repository:chosen,readme_excerpt:'Kısa özet.',preview_token:'preview-proof'};return {project};});}
async function prepare(){render(<ProjectEditor/>);fireEvent.change(await screen.findByLabelText('GitHub reposu'),{target:{value:'2:1'}});fireEvent.click(screen.getByRole('button',{name:'Paylaşımı hazırla'}));await screen.findByRole('button',{name:'Projeyi paylaş'});}
function select(label:string,value:string){fireEvent.change(screen.getByLabelText(label),{target:{value}});}
it('shows real empty state',async()=>{vi.mocked(api).mockResolvedValue({projects:[]});render(<MyProjects/>);expect(await screen.findByText(/Henüz bir proje paylaşmadınız/)).toBeInTheDocument();});
it('hides private repository URLs until explicit access-checked refresh',async()=>{vi.mocked(api).mockResolvedValue({project,participation:null});render(<ProjectDetail id="123"/>);await screen.findByText(project.title);expect(screen.queryByRole('link',{name:/Devamını oku/})).not.toBeInTheDocument();expect(screen.queryByText('owner/secret')).not.toBeInTheDocument();expect(api).toHaveBeenCalledTimes(1);});
it('shows safe public repository continuation link',async()=>{vi.mocked(api).mockResolvedValue({project:{...project,is_private:false},participation:null});render(<ProjectDetail id="123"/>);expect(await screen.findByRole('link',{name:/Devamını oku/})).toHaveAttribute('href',project.repository_url);});
it('blocks sharing without verified email',async()=>{state.user!.email_verified=false;editorApi();render(<ProjectEditor/>);expect(await screen.findByText(/Yeni paylaşım için e-posta adresiniz doğrulanmış/)).toBeInTheDocument();expect(screen.queryByLabelText('GitHub reposu')).not.toBeInTheDocument();});
it('reports disabled GitHub app',async()=>{vi.mocked(api).mockImplementation(async path=>path==='projects/config'?config:{enabled:false,connected:false});render(<ProjectEditor/>);expect(await screen.findByText(/henüz kullanıma hazır değil/)).toBeInTheDocument();});
it('requires preview consent, taxonomy and one need/mode, excludes private PR option',async()=>{editorApi();await prepare();const submit=screen.getByRole('button',{name:'Projeyi paylaş'});expect(submit).toBeDisabled();select('Üst kategori','software');select('Alt kategori','web');select('Proje durumu','idea');select('Aranan katkı','contributor');select('Katılım yöntemi','application');expect(screen.queryByRole('option',{name:'PR'})).not.toBeInTheDocument();expect(screen.queryByRole('option',{name:'Hata'})).not.toBeInTheDocument();fireEvent.click(screen.getByLabelText('README özetini paylaş'));select('İlanı kimler görebilsin?','selected');expect(screen.getByText(/İlan bilgilerini yalnız sahibi/)).toBeInTheDocument();fireEvent.click(screen.getByLabelText(/Gösterilen bilgileri/));fireEvent.click(submit);await waitFor(()=>expect(state.push).toHaveBeenCalledWith('/projeler/123'));expect(api).toHaveBeenCalledWith('projects',expect.objectContaining({need_type:'contributor',participation_mode:'application',visibility:'selected',readme_excerpt:'',preview_token:'preview-proof'}),'POST');});
it('shares feature descriptions without Issue requirements',async()=>{editorApi();await prepare();select('Üst kategori','software');select('Alt kategori','web');select('Proje durumu','idea');select('Aranan katkı','feature');select('Katılım yöntemi','application');select('Mevcut durum / sorun','Arama yok');select('Beklenen sonuç','Arama eklensin');expect(screen.queryByLabelText('GitHub Issue')).not.toBeInTheDocument();fireEvent.click(screen.getByLabelText(/Gösterilen bilgileri/));fireEvent.click(screen.getByRole('button',{name:'Projeyi paylaş'}));await waitFor(()=>expect(api).toHaveBeenCalledWith('projects',expect.objectContaining({current_state:'Arama yok',desired_outcome:'Arama eklensin'}),'POST'));});
it('keeps need/mode immutable and can archive without verification',async()=>{editorApi();state.user!.email_verified=false;render(<ProjectEditor id="123"/>);expect(await screen.findByLabelText('Aranan katkı')).toBeDisabled();expect(screen.getByLabelText('Katılım yöntemi')).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:'Paylaşımı arşivle'}));await waitFor(()=>expect(api).toHaveBeenCalledWith('projects/123',{is_active:false},'PATCH'));});
it('offers sign-in for anonymous account pages',()=>{state.user=null;render(<MyProjects/>);expect(screen.getByRole('link',{name:'Giriş yap'})).toHaveAttribute('href','/giris');});

it('loads only the recent Issue selector on explicit request and submits the selected number',async()=>{editorApi(false);const original=vi.mocked(api).getMockImplementation()!;vi.mocked(api).mockImplementation(async(path,...rest)=>path==='projects/github/issues'?{issues:[{number:42,title:'Arama bozuk'}],limit:50}:original(path,...rest));await prepare();select('Üst kategori','software');select('Alt kategori','web');select('Proje durumu','idea');select('Aranan katkı','bug');select('Katılım yöntemi','application');select('Mevcut durum / sorun','Arama bozuk');select('Beklenen sonuç','Arama çalışsın');expect(api).not.toHaveBeenCalledWith('projects/github/issues',expect.anything());fireEvent.click(screen.getByLabelText(/Gösterilen bilgileri/));expect(screen.getByRole('button',{name:'Projeyi paylaş'})).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:'Açık Issue’ları yükle'}));await screen.findByLabelText('Bağlanacak açık Issue');select('Bağlanacak açık Issue','42');expect(api).toHaveBeenCalledWith('projects/github/issues',{installation_id:2,repository_id:1});fireEvent.click(screen.getByLabelText(/Gösterilen bilgileri/));fireEvent.click(screen.getByRole('button',{name:'Projeyi paylaş'}));await waitFor(()=>expect(api).toHaveBeenCalledWith('projects',expect.objectContaining({need_type:'bug',issue_number:42}),'POST'));});
it('ignores stale issue results and clears bug and PR when selecting a private repo',async()=>{editorApi(false);let resolve!:(value:unknown)=>void;const original=vi.mocked(api).getMockImplementation()!;vi.mocked(api).mockImplementation(async(path,body,...rest)=>path==='projects/github/issues'?new Promise(done=>{resolve=done;}):path==='projects/github/repositories'?{repositories:[{...repo,private:false},{...repo,id:2}]}:path==='projects/github/preview'?{repository:{...repo,id:(body as {repository_id:number}).repository_id,private:(body as {repository_id:number}).repository_id===2},preview_token:'proof',readme_excerpt:''}:original(path,body,...rest));await prepare();select('Aranan katkı','bug');select('Katılım yöntemi','pr');fireEvent.click(screen.getByRole('button',{name:'Açık Issue’ları yükle'}));fireEvent.click(screen.getByRole('button',{name:'Repoyu değiştir'}));select('GitHub reposu','2:2');resolve({issues:[{number:42,title:'Eski Issue'}],limit:50});fireEvent.click(screen.getByRole('button',{name:'Paylaşımı hazırla'}));expect(await screen.findByLabelText('Aranan katkı')).toHaveValue('');expect(screen.getByLabelText('Katılım yöntemi')).toHaveValue('');expect(screen.queryByRole('option',{name:'Hata'})).not.toBeInTheDocument();expect(screen.queryByText('Eski Issue')).not.toBeInTheDocument();});

it('collapses prepared repo controls while preserving form values when changing and closing the selector',async()=>{editorApi(false);await prepare();expect(screen.queryByLabelText('GitHub reposu')).not.toBeInTheDocument();select('Proje başlığı','Özel başlığım');select('Aranan katkı','feature');select('Mevcut durum / sorun','Mevcut');select('Beklenen sonuç','Hedef');fireEvent.click(screen.getByRole('button',{name:'Repoyu değiştir'}));expect(screen.getByLabelText('GitHub reposu')).toHaveValue('2:1');fireEvent.click(screen.getByRole('button',{name:'Seçimi kapat'}));expect(screen.getByLabelText('Proje başlığı')).toHaveValue('Özel başlığım');expect(screen.getByLabelText('Mevcut durum / sorun')).toHaveValue('Mevcut');expect(screen.getByLabelText('Beklenen sonuç')).toHaveValue('Hedef');expect(screen.getByLabelText(/Gösterilen bilgileri/)).not.toBeChecked();expect(screen.getByText('README özetini incele').closest('details')).not.toHaveAttribute('open');});
