# Generated by Django 5.2.17 on 2026-09-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_change_nonce',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
    ]
