'use client';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import {api,ApiError} from '../lib/api';
import {Collaboration,Project,Participation,githubResourceUrl,githubStatus,participationStatus} from '../lib/projects';
import {RequireSession,useSession} from './session-provider';
import {ActionLink,Alert,Button,Field,Input,PageHeading,Surface} from './ui';

const visibilityLabels:Record<string,string>={public:'Herkese açık',link:'Bağlantıya sahip olanlar',selected:'Yalnız seçilen kişiler'};
const kindLabels:Record<string,string>={application:'Başvuru',automatic:'Otomatik katılım',pr:'PR ile katılım',invitation:'Katılım daveti'};
function errorText(error:unknown){return error instanceof ApiError?[error.message,...Object.values(error.errors).flat()].join(' '):(error as Error).message;}
function External({url,children}:{url:string;children:ReactNode}){const safe=githubResourceUrl(url);return safe?<a href={safe} target="_blank" rel="noopener noreferrer" referrerPolicy="no-referrer">{children}</a>:null;}
function RecordStatus({row,recipient=false}:{row:Participation;recipient?:boolean}){return <><p><strong>{participationStatus[row.status]||row.status}</strong>{row.github_status&&<> · {githubStatus[row.github_status]||row.github_status}</>}{row.merged&&' · PR birleştirildi'}</p>{row.operation_state==='pending'&&<Alert>GitHub işlemi tamamlanmayı bekliyor. Aynı kararla yeniden deneyin.</Alert>}{row.operation_state==='failed'&&<Alert tone="error">GitHub işlemi tamamlanamadı. Aynı kararla yeniden deneyin.</Alert>}{recipient&&row.github_status==='invited'&&<p><External url={row.github_invitation_url}>GitHub erişim davetini aç ve kabul et</External>. Ardından GitHub durumunu yenileyin.</p>}</>;}

export function ListingParticipation({project,initial,onProject}:{project:Project;initial:Participation|null;onProject:(project:Project)=>void}){
 const {user}=useSession();const [row,setRow]=useState(initial);const [busy,setBusy]=useState(false);const lock=useRef(false);const [error,setError]=useState('');const [message,setMessage]=useState('');const [explanation,setExplanation]=useState('');const [pr,setPr]=useState('');const [collaboration,setCollaboration]=useState<Collaboration|null>(null);const [viewer,setViewer]=useState('');const [invite,setInvite]=useState('');const [viewers,setViewers]=useState<{username:string}[]|null>(null);
 async function perform(work:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError('');setMessage('');try{await work();}catch(error){setError(errorText(error));}finally{lock.current=false;setBusy(false);}}
 async function reconcile(){try{const data=await api<{project:Project;participation:Participation|null}>(`projects/${project.id}`);setRow(data.participation);onProject(data.project);}catch{/* Preserve the mutation error; dashboard provides a durable retry. */}}
 const issueRequired=['feature','bug'].includes(project.need_type||'');
 return <div className="participation-section"><h2>Katılım ve ihtiyaç</h2><dl className="project-taxonomy"><div><dt>Aranan katkı</dt><dd>{project.need_type_label}</dd></div><div><dt>Katılım yöntemi</dt><dd>{project.participation_mode_label}</dd></div><div><dt>Görünürlük</dt><dd>{visibilityLabels[project.visibility]}</dd></div></dl><p>{project.visibility==='selected'?'Yalnız davetle katılım':project.applications_open?'Başvurular açık':'Yeni başvurular kapalı'} · İlan sahibi: {project.owner_username}</p>
 {issueRequired&&<><h3>Mevcut durum</h3><p className="project-text">{project.current_state}</p><h3>Beklenen sonuç</h3><p className="project-text">{project.desired_outcome}</p>{project.issue_status!=='ready'&&<Alert>GitHub Issue bağlantısı henüz tamamlanmadı. Başvurular bağlantı tamamlanınca açılır.</Alert>}</>}
 {project.participation_mode==='automatic'&&<p>Katılım, otomatik GitHub erişim daveti gönderir. Daveti GitHub’da kabul etmeniz gerekir. Çalışmalar ayrı branch ve PR üzerinden ilerler; korunan dallar için repo kuralları geçerlidir.</p>}
 {project.participation_mode==='pr'&&<p>Bu public repoya bağlı GitHub hesabınızdan açık, taslak olmayan bir PR gönderin. İlan sahibi PR’ı inceleyip birleştirebilir; ayrıca erişim daveti göndermeyi seçebilir.</p>}
 {error&&<Alert role="alert" tone="error">{error}</Alert>}{message&&<Alert role="status" tone="success">{message}</Alert>}
 {project.is_owner?<><div className="action-row"><ActionLink href={`/projelerim/${project.id}/duzenle`}>İlanı düzenle</ActionLink><ActionLink variant="secondary" href="/basvurular">Gelen başvuruları yönet</ActionLink>{issueRequired&&project.issue_status!=='ready'&&<Button disabled={busy} onClick={()=>perform(async()=>{try{const data=await api<{project:Project}>(`projects/${project.id}/issue`,{});onProject(data.project);setMessage(data.project.issue_status==='ready'?'Issue bağlantısı tamamlandı.':'Issue işlemi bekliyor.');}catch(error){await reconcile();throw error;}})}>Issue bağlantısını yeniden dene</Button>}</div>
 <div className="participation-grid"><Surface className="project-panel"><h3>Görüntüleme izni</h3><p>Yalnız ilanı açar; GitHub repo erişimi veya katılım sağlamaz. İlanı sadece bu kişilere açmak için görünürlüğü “Yalnız seçilen kişiler” yapın.</p><form onSubmit={event=>{event.preventDefault();void perform(async()=>{await api(`projects/${project.id}/viewers`,{username:viewer});const data=await api<{viewers:{username:string}[]}>(`projects/${project.id}/viewers`);setViewers(data.viewers);setViewer('');setMessage('Görüntüleme izni verildi.');});}}><Field id="viewer-username" label="FIRST kullanıcı adı"><Input id="viewer-username" required value={viewer} onChange={e=>setViewer(e.target.value)} disabled={busy}/></Field><Button type="submit" disabled={busy}>Görüntüleme izni ver</Button></form><Button variant="quiet" disabled={busy} onClick={()=>perform(async()=>{const data=await api<{viewers:{username:string}[]}>(`projects/${project.id}/viewers`);setViewers(data.viewers);})}>İzin verilenleri listele</Button>{viewers&&<ul className="plain-list">{viewers.length===0&&<li>Ek görüntüleme izni yok.</li>}{viewers.map(item=><li key={item.username}><span>{item.username}</span><Button variant="danger" disabled={busy} onClick={()=>perform(async()=>{await api(`projects/${project.id}/viewers`,{username:item.username},'DELETE');setViewers(items=>items?.filter(value=>value.username!==item.username)||[]);setMessage('Görüntüleme izni kaldırıldı. Ayrı katılım daveti ve GitHub erişimi devam edebilir.');})}>İzni kaldır</Button></li>)}</ul>}</Surface>
 <Surface className="project-panel"><h3>Katılım daveti</h3><p>FIRST kullanıcı adına davet gönderilir. Kişi kabul edince GitHub erişim daveti gönderilir. Görüntüleme izninden ayrıdır.</p><form onSubmit={event=>{event.preventDefault();void perform(async()=>{const data=await api<{participation:Participation}>(`projects/${project.id}/invitations`,{username:invite});setMessage(`Katılım kaydı: ${participationStatus[data.participation.status]||data.participation.status}. Başvurular ekranından takip edebilirsiniz.`);setInvite('');});}}><Field id="invite-username" label="FIRST kullanıcı adı"><Input id="invite-username" required value={invite} onChange={e=>setInvite(e.target.value)} disabled={busy}/></Field><Button type="submit" disabled={busy||!project.is_active||issueRequired&&project.issue_status!=='ready'}>Katılım daveti gönder</Button></form></Surface></div></>:row?<><RecordStatus row={row} recipient/><ActionLink variant="secondary" href="/basvurular">Başvurumu / davetimi yönet</ActionLink></>:project.can_apply?(!user?<Alert><p>Başvurmak için giriş yapın.</p><ActionLink href="/giris">Giriş yap</ActionLink></Alert>:!user.email_verified||!user.providers.includes('github')?<Alert><p>Başvuru için doğrulanmış e-posta ve bağlı GitHub hesabı gerekir.</p><ActionLink href="/hesap">Hesabımı tamamla</ActionLink></Alert>:<form onSubmit={event=>{event.preventDefault();void perform(async()=>{try{const data=await api<{participation:Participation}>(`projects/${project.id}/apply`,{explanation,...(project.participation_mode==='pr'?{pr_number:Number(pr)}:{})});setRow(data.participation);}catch(error){await reconcile();throw error;}});}}><Field id="application-explanation" label="Katılım açıklamanız"><textarea className="input" id="application-explanation" rows={4} required maxLength={5000} value={explanation} disabled={busy} onChange={e=>setExplanation(e.target.value)}/></Field>{project.participation_mode==='pr'&&<Field id="application-pr" label="Bu repodaki PR numaranız"><Input id="application-pr" type="number" min={1} step={1} required value={pr} disabled={busy} onChange={e=>setPr(e.target.value)}/></Field>}<Button type="submit" loading={busy}>{project.participation_mode==='automatic'?'Katıl ve GitHub erişim daveti al':'Başvuruyu gönder'}</Button></form>):<Alert>Bu ilan şu anda yeni başvuru almıyor.</Alert>}
 <section className="participation-section"><h2>GitHub Issue ve açık PR’lar</h2><p>Veriler yalnız bu düğmeyle GitHub’dan alınır. Private repo verileri için güncel GitHub erişiminiz ayrıca doğrulanır.</p><Button variant="secondary" disabled={busy} onClick={()=>{setCollaboration(null);void perform(async()=>{setCollaboration(await api<Collaboration>(`projects/${project.id}/collaboration`,{}));});}}>GitHub verilerini getir / yenile</Button>{collaboration&&<><p><External url={collaboration.repository_url}>GitHub reposunu aç</External></p>{collaboration.issue&&<p>Issue #{collaboration.issue.number}: <External url={collaboration.issue.url}>{collaboration.issue.title}</External> · {collaboration.issue.state}</p>}{collaboration.pull_requests.length===0?<p>Açık PR bulunamadı.</p>:<ul>{collaboration.pull_requests.map(pr=><li key={pr.number}><External url={pr.url}>#{pr.number} {pr.title}</External>{pr.draft&&' · Taslak'}<p className="commit-sha">Commit: {pr.sha}</p></li>)}</ul>}</>}</section></div>;
}

export function ParticipationDashboard(){return <RequireSession><DashboardContent/></RequireSession>;}
function DashboardContent(){
 const [data,setData]=useState<{sent:Participation[];received:Participation[]}|null>(null);const [error,setError]=useState('');const [retry,setRetry]=useState(0);
 useEffect(()=>{let active=true;api<{sent:Participation[];received:Participation[]}>('projects/participation').then(value=>{if(active)setData(value);}).catch(error=>{if(active)setError(errorText(error));});return()=>{active=false;};},[retry]);
 return <div className="account-page project-page"><PageHeading title="Başvurular ve davetler" eyebrow="FIRST / KATILIM" description="Gelen başvuruları değerlendirin, davetlerinizi ve GitHub erişiminizi takip edin."/>{error&&<Alert tone="error" role="alert">{error}<Button variant="secondary" onClick={()=>{setError('');setRetry(value=>value+1);}}>Yeniden dene</Button></Alert>}{!data&&!error&&<Alert role="status">Başvurular yükleniyor…</Alert>}{data&&(['received','sent'] as const).map(section=><section key={section}><h2>{section==='received'?'Projelerime gelenler':'Başvurularım ve aldığım davetler'}</h2>{data[section].length===0?<p>Henüz kayıt yok.</p>:data[section].map(row=><ParticipationCard key={row.id} initial={row} owner={section==='received'}/>)}</section>)}</div>;
}
function ParticipationCard({initial,owner}:{initial:Participation;owner:boolean}){
 const [row,setRow]=useState(initial);const [sha,setSha]=useState('');const [reviewed,setReviewed]=useState(false);const [reviewUrl,setReviewUrl]=useState('');const [busy,setBusy]=useState(false);const lock=useRef(false);const [error,setError]=useState('');const [mustReload,setMustReload]=useState(false);
 const pinned=['pending','failed'].includes(row.operation_state);const pending=['pending','invited'].includes(row.status);const canDecide=owner?['application','pr'].includes(row.kind):['invitation','automatic'].includes(row.kind);const isPr=row.kind==='pr';
 async function reload(){const data=await api<{sent:Participation[];received:Participation[]}>('projects/participation');const fresh=data[owner?'received':'sent'].find(item=>item.id===row.id);if(!fresh)throw new Error('Katılım kaydı artık erişilebilir değil.');setRow(fresh);setMustReload(false);return fresh;}
 async function perform(work:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await work();}catch(error){setError(errorText(error));}finally{lock.current=false;setBusy(false);}}
 async function action(value:string){await perform(async()=>{try{const data=await api<{participation:Participation}>(`projects/participation/${row.id}/action`,{action:value,...(isPr&&value.startsWith('accept')?{expected_sha:pinned?row.pr_sha:sha}:{})});setRow(data.participation);setReviewed(false);}catch(error){setReviewed(false);setMustReload(true);try{await reload();}catch{setError('Kayıt yenilenemedi. Yeniden işlem yapmadan önce kaydı yenileyin.');}throw error;}});}
 return <Surface className="project-panel"><h3><a href={`/projeler/${row.project_id}`}>{row.project_title}</a></h3><p>{owner?row.username:'Siz'} · {kindLabels[row.kind]}</p>{row.explanation&&<p className="project-text">{row.explanation}</p>}<RecordStatus row={row} recipient={!owner}/>{error&&<Alert role="alert" tone="error">{error}</Alert>}
 {isPr&&<p>PR #{row.pr_number}{row.pr_sha&&<> · Kayıtlı commit: <span className="commit-sha">{row.pr_sha}</span></>}</p>}
 {canDecide&&pending&&isPr&&!pinned&&<><Button variant="secondary" disabled={busy||mustReload} onClick={()=>perform(async()=>{setReviewed(false);setReviewUrl('');setSha('');const data=await api<Collaboration>(`projects/${row.project_id}/collaboration`,{});const pull=data.pull_requests.find(item=>item.number===row.pr_number);if(!pull)throw new Error('PR açık listede bulunamadı. GitHub’da durumunu kontrol edin.');setSha(pull.sha);setReviewUrl(pull.url);})}>İncelenecek PR ve güncel commit’i getir</Button>{reviewUrl&&<p><External url={reviewUrl}>PR değişikliklerini GitHub’da incele</External></p>}<Field id={`sha-${row.id}`} label="İncelediğiniz commit SHA"><Input id={`sha-${row.id}`} value={sha} pattern="[a-fA-F0-9]{40,64}" onChange={e=>{setSha(e.target.value);setReviewed(false);}} disabled={busy}/></Field><label className="check"><input type="checkbox" checked={reviewed} disabled={!/^[a-fA-F0-9]{40,64}$/.test(sha)||busy} onChange={e=>setReviewed(e.target.checked)}/><span>Bu commit’in değişikliklerini inceledim; seçtiğim işlem PR’ı birleştirecek.</span></label></>}
 <div className="action-row">{mustReload?<Button disabled={busy} onClick={()=>perform(async()=>{await reload();})}>Güncel kaydı yeniden yükle</Button>:<>{canDecide&&pending&&(pinned?<Button disabled={busy||!row.decision} onClick={()=>action(row.decision)}>Aynı işlemi yeniden dene ({row.decision==='accept_and_invite'?'birleştir ve davet et':isPr?'birleştir':'erişim daveti'})</Button>:<><Button disabled={busy||(isPr&&!reviewed)} onClick={()=>action('accept')}>{isPr?'PR’ı kabul et ve birleştir':owner?'Kabul et ve GitHub erişim daveti gönder':'Daveti kabul et ve GitHub erişim daveti al'}</Button>{isPr&&<Button variant="secondary" disabled={busy||!reviewed} onClick={()=>action('accept_and_invite')}>Birleştir ve erişim daveti gönder</Button>}</>)}{pending&&!pinned&&row.operation_state==='idle'&&(owner?row.kind!=='invitation':true)&&<Button variant="danger" disabled={busy} onClick={()=>action(owner?'reject':row.kind==='invitation'?'decline':'withdraw')}>{owner?'Başvuruyu reddet':row.kind==='invitation'?'Daveti reddet':'Başvuruyu geri çek'}</Button>}{row.github_status&&row.operation_state==='succeeded'&&<Button variant="secondary" disabled={busy} onClick={()=>action('refresh')}>GitHub erişim durumunu yenile</Button>}</>}</div><p className="field-help">İlanın kapanması veya FIRST işlemleri mevcut GitHub erişimini kaldırmaz.</p></Surface>;
}

export function Notifications(){return <RequireSession><NotificationsContent/></RequireSession>;}
function NotificationsContent(){
 type Notice={id:string;project_id:string;message:string;is_read:boolean;created_at:string};const [items,setItems]=useState<Notice[]|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [retry,setRetry]=useState(0);
 useEffect(()=>{let active=true;api<{notifications:Notice[]}>('projects/notifications').then(data=>{if(active)setItems(data.notifications);}).catch(error=>{if(active)setError(errorText(error));});return()=>{active=false;};},[retry]);
 return <div className="account-page project-page"><PageHeading title="Bildirimler" eyebrow="FIRST / BİLDİRİMLER"/><ActionLink variant="secondary" href="/basvurular">Başvurulara ve davetlere git</ActionLink>{error&&<Alert role="alert" tone="error">{error}<Button variant="secondary" onClick={()=>{setError('');setRetry(value=>value+1);}}>Yeniden dene</Button></Alert>}{!items&&!error&&<Alert role="status">Bildirimler yükleniyor…</Alert>}{items?.length===0&&<p>Henüz bildirim yok.</p>}{items?.map(item=><Surface key={item.id} className="project-panel"><p>{!item.is_read&&<strong>Yeni · </strong>}{item.message}</p><p><time dateTime={item.created_at}>{new Date(item.created_at).toLocaleString('tr-TR')}</time></p><div className="action-row"><ActionLink variant="quiet" href={`/projeler/${item.project_id}`}>İlana git</ActionLink>{!item.is_read&&<Button variant="secondary" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await api(`projects/notifications/${item.id}/read`,{});setItems(list=>list?.map(value=>value.id===item.id?{...value,is_read:true}:value)||[]);}catch(error){setError(errorText(error));}finally{setBusy(false);}}}>Okundu işaretle</Button>}</div></Surface>)}</div>;
}
