'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {api} from '../lib/api';
import {labels,profileHref,safeWebsite,type CommunityConfig,type PageInfo,type ProfilePage,type PublicProfile} from '../lib/community';
import type {Project} from '../lib/projects';
import {ProjectCard} from './project-card';
import {MultiChoice,Pagination,ReportForm} from './community-controls';
import {RequireSession,SessionPending,useSession} from './session-provider';
import {ActionLink,Alert,Button,Checkbox,Field,Input,PageHeading,Select,Surface} from './ui';
function ProfileAvatar({profile}:{profile:PublicProfile}) {
 const [failed,setFailed]=useState('');
 const url=safeWebsite(profile.avatar_url);
 const avatar=url&&new URL(url).protocol==='https:'&&new URL(url).hostname==='avatars.githubusercontent.com'?url:null;
 return <span className="person-initial profile-initial" aria-hidden="true">{avatar&&failed!==avatar?
  // Provider avatars use native image loading, matching the connected-account UI.
  // eslint-disable-next-line @next/next/no-img-element
  <img src={avatar} alt="" width={96} height={96} referrerPolicy="no-referrer" onError={()=>setFailed(avatar)}/>
  :(profile.full_name||profile.username).slice(0,1).toLocaleUpperCase('tr')}</span>;
}
function ErrorBox({error,retry}:{error:string;retry:()=>void}){return <Alert role="alert" tone="error"><p>{error}</p><Button variant="secondary" onClick={retry}>Yeniden dene</Button></Alert>;}
export function People(){
 const [config,setConfig]=useState<CommunityConfig|null>(null);const [filters,setFilters]=useState({q:'',skill:'',interest:''});const [draft,setDraft]=useState('');const [page,setPage]=useState(1);const [data,setData]=useState<(PageInfo&{people:PublicProfile[]})|null>(null);const [error,setError]=useState('');const [retry,setRetry]=useState(0);
 useEffect(()=>{let active=true;setData(null);setError('');const query=new URLSearchParams({...filters,page:String(page)});Promise.all([api<CommunityConfig>('community/config'),api<PageInfo&{people:PublicProfile[]}>('people',undefined,'GET',query)]).then(([c,d])=>{if(active){setConfig(c);setData(d);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[filters,page,retry]);
 function filter(key:'skill'|'interest',value:string){setFilters(v=>({...v,[key]:value}));setPage(1);}
 return <div className="community-page"><PageHeading eyebrow="FIRST / TOPLULUK" title="Kişileri keşfet" description="Becerileri ve ilgi alanları size uyan geliştiricilerle tanışın."/><Surface className="project-panel"><form className="community-search" onSubmit={e=>{e.preventDefault();setFilters(v=>({...v,q:draft.trim()}));setPage(1);}}><Field id="people-search" label="Ad veya kullanıcı adı"><Input id="people-search" type="search" maxLength={100} value={draft} onChange={e=>setDraft(e.target.value)}/></Field><Button type="submit">Ara</Button></form><div className="listing-filters">{(['skill','interest'] as const).map(key=><Field key={key} id={`people-${key}`} label={key==='skill'?'Beceri':'İlgi alanı'}><Select id={`people-${key}`} value={filters[key]} onChange={e=>filter(key,e.target.value)}><option value="">Tümü</option>{(key==='skill'?config?.skills:config?.interests)?.map(item=><option key={item.value} value={item.value}>{item.label}</option>)}</Select></Field>)}</div><Button variant="quiet" onClick={()=>{setDraft('');setFilters({q:'',skill:'',interest:''});setPage(1);}}>Filtreleri temizle</Button><p className="field-help">Keşfe açık ve GitHub hesabı bağlı kişiler listelenir.</p></Surface>{error?<ErrorBox error={error} retry={()=>setRetry(v=>v+1)}/>:!data?<Alert role="status">Kişiler yükleniyor…</Alert>:<><p aria-live="polite">{data.count} kişi bulundu.</p><div className="repository-grid">{data.people.map(person=><Surface key={person.username} className="person-card"><div className="person-identity"><span className="person-initial" aria-hidden="true">{(person.full_name||person.username).slice(0,1).toLocaleUpperCase('tr')}</span><div><h2><Link href={profileHref(person.username)}>{person.full_name||person.username}</Link></h2><p>@{person.username}</p></div></div><p className="project-text">{person.bio||'Henüz bir tanıtım eklenmedi.'}</p><p>{labels(person.skills,config?.skills)}</p><span className="field-help">{person.invitations_open?'Katılım davetlerine açık':'Katılım davetleri kapalı'}</span></Surface>)}</div>{!data.people.length&&<Surface className="empty-state"><p>Bu aramayla eşleşen kişi bulunamadı.</p></Surface>}<Pagination data={data} page={page} onChange={setPage}/></>}</div>;
}
export function PublicProfilePage({username}:{username:string}){const {status,user}=useSession();if(status!=='ready')return <SessionPending/>;return <ProfileContent key={`${username}:${user?.id??'visitor'}`} username={username}/>;}
function ProfileContent({username}:{username:string}){
 const {user}=useSession();const [page,setPage]=useState(1);const [data,setData]=useState<ProfilePage|null>(null);const [config,setConfig]=useState<CommunityConfig|null>(null);const [error,setError]=useState('');const [retry,setRetry]=useState(0);
 useEffect(()=>{let active=true;setData(null);setError('');Promise.all([api<ProfilePage>(`people/${encodeURIComponent(username)}`,undefined,'GET',new URLSearchParams({page:String(page)})),api<CommunityConfig>('community/config')]).then(([d,c])=>{if(active){setData(d);setConfig(c);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[username,page,retry]);
 if(error)return <ErrorBox error={error} retry={()=>setRetry(v=>v+1)}/>;if(!data)return <Alert role="status">Profil yükleniyor…</Alert>;
 const p=data.profile;const own=user?.username===p.username;const website=safeWebsite(p.website);const github=p.github_username&&safeWebsite(p.github_url);
 return <div className="community-page profile-page"><ActionLink variant="quiet" href="/kisiler">← Kişilere dön</ActionLink>
 <Surface className="profile-hero"><div className="profile-identity"><ProfileAvatar profile={p}/><div><PageHeading eyebrow={`@${p.username}`} title={p.full_name||p.username}/><span className={`connection-status${p.invitations_open?' connection-status--connected':''}`}>{p.invitations_open?'Katılım davetlerine açık':'Yeni katılım davetleri kapalı'}</span><p className="profile-bio">{p.bio||'Henüz bir tanıtım eklenmedi.'}</p><div className="profile-links">{github&&<a href={github} target="_blank" rel="noopener noreferrer">GitHub — {p.github_username}</a>}{website&&<a href={website} target="_blank" rel="noopener noreferrer">Web sitesi</a>}</div></div></div><div className="profile-actions">{own&&<ActionLink href="/profil/duzenle" variant="secondary">Profilimi düzenle</ActionLink>}{!own&&p.invitations_open&&p.github_username&&<ProfileInvite username={p.username}/>}<ReportForm type="profile" id={p.username} own={own}/></div></Surface>
 <div className="profile-columns"><aside className="profile-sidebar" aria-label="Profil bilgileri"><Surface className="profile-section"><h2>Hakkında</h2><p className="project-text">{p.bio||'Henüz bir tanıtım eklenmedi.'}</p></Surface><Surface className="profile-section"><h2>Beceriler &amp; Teknolojiler</h2><div className="profile-tags">{p.skills.length?p.skills.map(value=><span key={value}>{labels([value],config?.skills)}</span>):<p className="field-help">Henüz beceri eklenmedi.</p>}</div></Surface><Surface className="profile-section"><h2>İlgi Alanları</h2><div className="profile-tags">{p.interests.length?p.interests.map(value=><span key={value}>{labels([value],config?.interests)}</span>):<p className="field-help">Henüz ilgi alanı eklenmedi.</p>}</div></Surface></aside>
 <Surface className="profile-section profile-projects"><h2>Paylaştığı Projeler <span className="count-badge">{data.count}</span></h2><div className="repository-grid">{data.projects.map(project=><ProjectCard key={project.id} project={project}/>)}</div>{!data.projects.length&&<p>Görüntülenebilen aktif proje yok.</p>}<Pagination data={data} page={page} onChange={setPage}/></Surface></div></div>;

}
function ProfileInvite({username}:{username:string}){
 const {user}=useSession();const [open,setOpen]=useState(false);const [projects,setProjects]=useState<Project[]|null>(null);const [selected,setSelected]=useState('');const [error,setError]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const lock=useRef(false);
 async function load(){setError('');try{setProjects((await api<{projects:Project[]}>('projects/mine')).projects.filter(p=>p.is_active&&(p.need_type!=='bug'||p.issue_status==='ready')));}catch(e){setError((e as Error).message);}}
 if(!user)return <ActionLink href="/giris" variant="quiet">Davet etmek için giriş yap</ActionLink>;
 if(!user.email_verified||!user.providers.includes('github'))return <p className="field-help">Davet göndermek için <a href="/hesap">e-posta ve GitHub bağlantınızı tamamlayın</a>.</p>;
 return <div className="community-invite"><Button variant="secondary" aria-expanded={open} onClick={()=>{setOpen(!open);if(!projects)void load();}}>Projeme davet et</Button>{open&&<form onSubmit={async e=>{e.preventDefault();if(lock.current||!selected)return;lock.current=true;setBusy(true);setError('');setMessage('');try{await api(`projects/${selected}/invitations`,{username});setMessage('Katılım daveti kaydedildi. Başvurular sayfasından takip edebilirsiniz.');}catch(e){setError((e as Error).message);}finally{lock.current=false;setBusy(false);}}}>{error&&<ErrorBox error={error} retry={()=>void load()}/>} {message&&<Alert role="status" tone="success">{message}</Alert>}{!projects?<p role="status">Projeler yükleniyor…</p>:!projects.length?<p>Davet gönderebileceğiniz aktif proje yok.</p>:<><Field id="profile-invite-project" label="Davet edilecek proje"><Select id="profile-invite-project" required disabled={busy} value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Proje seçin</option>{projects.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</Select></Field><Button type="submit" loading={busy} disabled={!selected}>Katılım daveti gönder</Button></>}</form>}</div>;
}
export function ProfileEditor(){return <RequireSession><ProfileEditorContent/></RequireSession>;}
function ProfileEditorContent(){
 const {user}=useSession();const [profile,setProfile]=useState<(PublicProfile&{discoverable:boolean})|null>(null);const [config,setConfig]=useState<CommunityConfig|null>(null);const [error,setError]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [retry,setRetry]=useState(0);const lock=useRef(false);
 useEffect(()=>{let active=true;setError('');Promise.all([api<{profile:PublicProfile&{discoverable:boolean}}>('community/profile'),api<CommunityConfig>('community/config')]).then(([d,c])=>{if(active){setProfile(d.profile);setConfig(c);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[retry]);
 return <div className="account-page"><PageHeading title="Topluluk profilim" description="Buradaki tanıtım ve beceriler herkese açık profilinizde görünür."/>{error&&<ErrorBox error={error} retry={()=>setRetry(v=>v+1)}/>} {message&&<Alert role="status" tone="success">{message}</Alert>}{!profile||!config?!error&&<Alert role="status">Profil yükleniyor…</Alert>:<Surface className="project-panel"><form onSubmit={async e=>{e.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setMessage('');setError('');const {bio,website,skills,interests,discoverable,invitations_open}=profile;try{setProfile((await api<{profile:PublicProfile&{discoverable:boolean}}>('community/profile',{bio,website,skills,interests,discoverable,invitations_open},'PATCH')).profile);setMessage('Topluluk profiliniz güncellendi.');}catch(e){setError((e as Error).message);}finally{lock.current=false;setBusy(false);}}}><fieldset disabled={busy}><p>Adınızı ve kullanıcı adınızı <Link href="/hesap">hesap ayarlarından</Link> değiştirebilirsiniz.</p><Field id="profile-bio" label="Kısa tanıtım"><textarea id="profile-bio" className="input" rows={4} maxLength={1000} value={profile.bio} onChange={e=>setProfile({...profile,bio:e.target.value})}/></Field><Field id="profile-website" label="Web sitesi (isteğe bağlı)" help="https:// veya http:// ile başlayan bağlantı"><Input id="profile-website" type="url" maxLength={500} value={profile.website} onChange={e=>setProfile({...profile,website:e.target.value})}/></Field><MultiChoice label="Beceriler" options={config.skills} value={profile.skills} onChange={skills=>setProfile({...profile,skills})}/><MultiChoice label="İlgi alanları" max={8} options={config.interests} value={profile.interests} onChange={interests=>setProfile({...profile,interests})}/><Checkbox checked={profile.discoverable} onChange={e=>setProfile({...profile,discoverable:e.target.checked})}>Kişi keşfinde görünebilirim</Checkbox><p className="field-help">Keşifte görünmek için GitHub bağlantısı gerekir. Bu seçeneği kapatsanız da profil bağlantınız herkese açık kalır.</p><Checkbox checked={profile.invitations_open} onChange={e=>setProfile({...profile,invitations_open:e.target.checked})}>Katılım davetlerine açığım</Checkbox><p className="field-help">Kapatmak yeni davetleri engeller; mevcut davetleriniz ve başvurularınız etkilenmez.</p><div className="action-row"><Button type="submit" loading={busy}>Profili kaydet</Button>{user&&<ActionLink variant="quiet" href={profileHref(user.username)}>Profilimi gör</ActionLink>}</div></fieldset></form></Surface>}</div>;
}
