'use client';
import {useEffect,useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import {api,ApiError} from '../lib/api';
import {ProjectCard} from './project-card';
import {RequireSession, SessionPending, useSession} from './session-provider';
import {githubUrl,GitHubStatus,Project,ProjectConfig,Repository,RepositoryCache,ProjectPreview,repositoryCacheCaption} from '../lib/projects';
import {ListingParticipation} from './participation';
import type {Participation,RepositoryIssues} from '../lib/projects';
import {ActionLink,Alert,Button,Checkbox,Field,Input,PageHeading,Select,Surface} from './ui';

function ProjectContent({project}:{project:Project}) {
 const link=!project.is_private && githubUrl(project.repository_url);
 return <><div className="project-sharing"><span className={`connection-status${project.is_active?' connection-status--connected':''}`}>{project.is_active?'Paylaşım aktif':'Arşivde'}</span><span>{project.is_private?'Paylaşım sırasında gizli repo':'Paylaşım sırasında açık repo'}</span></div>
 <dl className="project-taxonomy"><div><dt>Üst kategori</dt><dd>{project.category_label || 'Belirtilmedi'}</dd></div><div><dt>Alt kategori</dt><dd>{project.subcategory_label || 'Belirtilmedi'}</dd></div><div><dt>Proje durumu</dt><dd>{project.stage_label || 'Belirtilmedi'}</dd></div></dl>
 <p className="field-help">Bu sayfa FIRST’te kaydedilen paylaşım bilgilerini gösterir. GitHub’daki değişiklikler otomatik olarak buraya yansımaz.</p>
 <p className="project-text">{project.description}</p>{project.readme_excerpt && <><h2>README özeti</h2><p className="project-text">{project.readme_excerpt}</p></>}
 {link && <ActionLink href={link} target="_blank" rel="noopener noreferrer" referrerPolicy="no-referrer" variant="secondary">Devamını oku — GitHub</ActionLink>}
 {project.is_private && <p className="field-help">Bu paylaşım yalnızca açıklamayı ve onaylanan kısa özeti içerir. Repo bağlantısı ve dosyalar paylaşılmaz.</p>}</>;
}
export function MyProjects() {return <RequireSession><MyProjectsContent/></RequireSession>;}
function MyProjectsContent(){
 const [projects,setProjects]=useState<Project[]|null>(null);const [error,setError]=useState('');const [retry,setRetry]=useState(0);
 useEffect(()=>{let active=true;api<{projects:Project[]}>('projects/mine').then(data=>{if(active)setProjects(data.projects);}).catch(err=>{if(active)setError(err.message);});return()=>{active=false;};},[retry]);
 return <div className="account-page project-page"><div className="page-toolbar"><PageHeading title="Projelerim" eyebrow="FIRST / PROJELER" description="Paylaşımlarınızı görüntüleyin, güncelleyin ve yeni projelerinizi tanıtın."/><ActionLink href="/projelerim/yeni">Proje paylaş</ActionLink></div>
 {error&&<Alert role="alert" tone="error"><p>{error}</p><Button variant="secondary" onClick={()=>{setError('');setRetry(value=>value+1);}}>Yeniden dene</Button></Alert>}{!projects&&!error&&<Alert role="status">Projeleriniz yükleniyor…</Alert>}
 {projects?.length===0&&<Surface className="empty-state"><p className="eyebrow">İLK PAYLAŞIMINIZ</p><h2>Projelerinizi burada bir araya getirin.</h2><p>Henüz bir proje paylaşmadınız. GitHub hesabınızdan bir repo seçerek ilk paylaşımınızı hazırlayabilirsiniz.</p><ActionLink href="/projelerim/yeni">İlk projemi paylaş</ActionLink></Surface>}
 <div className="repository-grid">{projects?.map(project=><ProjectCard key={project.id} project={project} manage active={project.is_active} heading="h2"/>)}</div></div>;
}
export function ProjectDetail({id}:{id:string}) {
 const {status,user}=useSession();
 if(status !== 'ready') return <SessionPending/>;
 return <ProjectDetailContent key={`${id}:${status}:${user?.id ?? 'visitor'}`} id={id}/>;
}
function ProjectDetailContent({id}:{id:string}){
 const {user}=useSession();
 const [participation,setParticipation]=useState<Participation|null>(null);const [project,setProject]=useState<Project|null>(null);const [error,setError]=useState('');const [retry,setRetry]=useState(0);
 useEffect(()=>{let active=true;api<{project:Project;participation:Participation|null}>(`projects/${id}`).then(data=>{if(active){setProject(data.project);setParticipation(data.participation);}}).catch(err=>{if(active)setError(err.message);});return()=>{active=false;};},[id,retry]);
 return <div className="account-page project-page"><div className="back-link"><ActionLink variant="quiet" href={user?'/projelerim':'/'}>{user?'Projelerime dön':'Ana sayfaya dön'}</ActionLink></div>{error?<Alert role="alert" tone="error"><p>{error}</p><Button variant="secondary" onClick={()=>{setError('');setRetry(value=>value+1);}}>Yeniden dene</Button></Alert>:project?<Surface className="project-detail"><PageHeading title={project.title} eyebrow="FIRST / PROJE"/><ProjectContent project={project}/><ListingParticipation project={project} initial={participation} onProject={setProject}/></Surface>:<Alert role="status">Proje yükleniyor…</Alert>}</div>;
}
export function ProjectEditor({id}:{id?:string}) {return <RequireSession><ProjectEditorContent key={id || 'new'} id={id}/></RequireSession>;}
function ProjectEditorContent({id}:{id?:string}){
 const router=useRouter();const lock=useRef(false);const {user}=useSession();const [retry,setRetry]=useState(0);const [config,setConfig]=useState<ProjectConfig>();const [status,setStatus]=useState<GitHubStatus>();
 const [repoEditing,setRepoEditing]=useState(true);const titleEdited=useRef(false);
 const [repositories,setRepositories]=useState<Repository[]>([]);const [selected,setSelected]=useState('');const [cachedAt,setCachedAt]=useState<string|null>(null);const [preview,setPreview]=useState<ProjectPreview>();const [existing,setExisting]=useState<Project>();
 const [need,setNeed]=useState('');const [mode,setMode]=useState('');const [visibility,setVisibility]=useState('public');const [applicationsOpen,setApplicationsOpen]=useState(true);const [currentState,setCurrentState]=useState('');const [desiredOutcome,setDesiredOutcome]=useState('');const [issueChoice,setIssueChoice]=useState('existing');const [issueNumber,setIssueNumber]=useState('');
 const issueRevision=useRef(0);const issueLock=useRef(false);const [issueOptions,setIssueOptions]=useState<RepositoryIssues['issues']|null>(null);const [issuesRepo,setIssuesRepo]=useState('');const [issuesLoading,setIssuesLoading]=useState(false);const [issuesError,setIssuesError]=useState('');
 useEffect(()=>()=>{issueRevision.current++;},[]);
 function resetIssues(){issueRevision.current++;issueLock.current=false;setIssueOptions(null);setIssuesRepo('');setIssueNumber('');setIssueChoice('existing');setIssuesLoading(false);setIssuesError('');}
 function clearPrivateChoices(privateRepo:boolean){if(privateRepo){if(need==='bug')setNeed('');if(mode==='pr')setMode('');}}
 async function loadIssues(){
   if(issueLock.current||id||need!=='bug'||!preview||preview.repository.private)return;
   const repo=preview.repository;const repoKey=`${repo.installation_id}:${repo.id}`;
   if(repoKey!==selected)return;
   const revision=++issueRevision.current;issueLock.current=true;setIssuesLoading(true);setIssuesError('');setIssueOptions(null);setIssueNumber('');setIssuesRepo('');setConfirmed(false);
   try{const data=await api<RepositoryIssues>('projects/github/issues',{installation_id:repo.installation_id,repository_id:repo.id});if(revision!==issueRevision.current)return;setIssueOptions(data.issues.slice(0,50));setIssuesRepo(repoKey);}
   catch(error){if(revision===issueRevision.current)setIssuesError((error as Error).message);}
   finally{if(revision===issueRevision.current){issueLock.current=false;setIssuesLoading(false);}}
 }
 const [title,setTitle]=useState('');const [category,setCategory]=useState('');const [subcategory,setSubcategory]=useState('');const [stage,setStage]=useState('');const [fieldErrors,setFieldErrors]=useState<Record<string,string[]>>({});const [description,setDescription]=useState('');const [includeExcerpt,setIncludeExcerpt]=useState(true);const [confirmed,setConfirmed]=useState(false);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [ready,setReady]=useState(false);
 useEffect(()=>{let active=true;(async()=>{try{
   if(!id&&new URLSearchParams(window.location.search).get('github')==='failed')setError('GitHub repo bağlantısı tamamlanamadı. Yeniden deneyin.');
   const settings=await api<ProjectConfig>('projects/config');if(!active)return;setConfig(settings);
   if(id){const data=await api<{projects:Project[]}>('projects/mine');if(!active)return;const owned=data.projects.find(item=>item.id===id);if(!owned)throw new Error('Düzenleyebileceğiniz paylaşım bulunamadı.');setExisting(owned);setNeed(owned.need_type || '');setMode(owned.participation_mode || '');setVisibility(owned.visibility);setApplicationsOpen(owned.applications_open);setCurrentState(owned.current_state);setDesiredOutcome(owned.desired_outcome);setTitle(owned.title);setCategory(owned.category);setSubcategory(owned.subcategory || '');setStage(owned.stage || '');setDescription(owned.description);}
   else {const data=await api<GitHubStatus>('projects/github/status');if(!active)return;setStatus(data);if(data.connected){const repos=await api<RepositoryCache>('projects/github/repositories');if(active){setRepositories(repos.repositories);setCachedAt(repos.cached_at ?? null);}}}
 }catch(err){if(active)setError((err as Error).message);}finally{if(active)setReady(true);}})();return()=>{active=false;};},[id,retry]);
 async function perform(action:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError('');setFieldErrors({});try{await action();}catch(err){setError((err as Error).message);if(err instanceof ApiError){setFieldErrors(err.errors);if(!id&&err.status===409){setPreview(undefined);setConfirmed(false);setError(`${err.message} Repo seçiminizi kontrol edip Paylaşımı hazırla adımını yeniden tamamlayın.`);}}}finally{lock.current=false;setBusy(false);}}
 const categories=Array.isArray(config?.categories)?config.categories:[];
 const stages=Array.isArray(config?.stages)?config.stages:[];
 const taxonomyReady=categories.length>0&&stages.length>0&&categories.every(item=>Array.isArray(item.subcategories)&&item.subcategories.length>0);
 const selectedCategory=categories.find(item=>item.value===category);
 const subcategories=selectedCategory?.subcategories || [];
 const selectedStage=stages.find(item=>item.value===stage);
 const taxonomySelected=taxonomyReady&&!!selectedCategory&&subcategories.some(item=>item.value===subcategory)&&!!selectedStage;
 const fieldError=(name:string)=>fieldErrors[name]?.join(' ');
 const fieldA11y=(name:string,help=false)=>({'aria-invalid':!!fieldError(name),'aria-describedby':[help?`project-${name}-help`:'',fieldError(name)?`project-${name}-error`:''].filter(Boolean).join(' ')||undefined});
 const privateRepo=existing?.is_private??preview?.repository.private??false;
 const issueSelectionReady=!!id||need!=='bug'||(!privateRepo&&!issuesLoading&&(issueChoice==='new'||(issuesRepo===selected&&issueOptions?.some(issue=>String(issue.number)===issueNumber)===true)));
 const eligible=!!user?.email_verified&&(!!id||!!user?.providers.includes('github'));
 return <div className="account-page project-page project-editor"><header className="project-editor-header"><PageHeading title={id?'Paylaşımı düzenle':'Proje paylaş'} eyebrow="FIRST / PROJELER"/><ActionLink variant="quiet" href="/projelerim">Projelerime dön</ActionLink></header>
 {error&&<Alert role="alert" tone="error"><p>{error}</p>{Object.entries(fieldErrors).filter(([name])=>!['title','category','subcategory','stage','description'].includes(name)).map(([name,messages])=><p key={name}>{messages.join(' ')}</p>)}{ready&&!busy&&Object.keys(fieldErrors).length===0&&(id?!existing:!config||!status)&&<Button variant="secondary" onClick={()=>{setError('');setRetry(value=>value+1);}}>Yeniden dene</Button>}</Alert>} {!ready&&<Alert role="status">Paylaşım bilgileri yükleniyor…</Alert>}
 {ready&&config&&!taxonomyReady&&<Alert role="status"><p>Proje kategorileri ve durumları hazırlanıyor. Seçenekler hazır olduğunda paylaşımınızı kaydedebilirsiniz.</p><Button variant="secondary" disabled={busy} onClick={()=>perform(async()=>{setConfig(await api<ProjectConfig>('projects/config'));})}>Seçenekleri yeniden yükle</Button></Alert>}
 {ready&&user===null&&<Alert><p>Proje paylaşmak için giriş yapın.</p><ActionLink href="/giris">Giriş yap</ActionLink></Alert>}
 {user&&!eligible&&<Alert><p>{id?'Paylaşımı düzenlemek için e-posta adresinizi doğrulayın.':'Yeni paylaşım için e-posta adresiniz doğrulanmış ve GitHub hesabınız bağlı olmalıdır.'} Hesabım bölümünden gerekli adımları tamamlayabilirsiniz.</p><ActionLink href="/hesap">Hesabımı düzenle</ActionLink></Alert>}
 {ready&&user&&!id&&eligible&&<Surface className="project-editor-repository">{preview&&!repoEditing?<div className="project-editor-repo-summary"><div><span className="field-help">GitHub reposu</span><p><strong>{preview.repository.full_name}</strong> <span className="connection-status">{preview.repository.private?'Gizli':'Açık'}</span></p></div><Button variant="secondary" disabled={busy} onClick={()=>setRepoEditing(true)}>Repoyu değiştir</Button></div>:<><div className="project-editor-repo-heading"><h2>GitHub reposu</h2>{preview&&<Button variant="quiet" disabled={busy} onClick={()=>setRepoEditing(false)}>Seçimi kapat</Button>}</div>
 {!status?.enabled||!config?.github_app_enabled?<Alert>GitHub repo bağlantısı henüz kullanıma hazır değil. Daha sonra tekrar deneyin.</Alert>:<>
 <p className="field-help">Yönetici olduğunuz bir repo seçin. Her repo için tek aktif ilan açabilirsiniz.</p><div className="project-editor-repo-tools">
 {status.connected ? <ActionLink href="/github-kurulum?next=%2Fprojelerim%2Fyeni&manage=1" variant="quiet">Repo izinlerini yönet</ActionLink> : <ActionLink href="/github-kurulum?next=%2Fprojelerim%2Fyeni">GitHub repo izinlerini tamamla</ActionLink>}
 {status.connected&&<><Button variant="quiet" loading={busy} disabled={busy} onClick={()=>{if(lock.current)return;setPreview(undefined);setConfirmed(false);resetIssues();void perform(async()=>{const data=await api<RepositoryCache>('projects/github/repositories',{});setRepositories(data.repositories);setCachedAt(data.cached_at ?? null);setSelected('');});}}>Repo listesini yenile</Button></>}</div>
 {status.connected&&<><div className="project-editor-repo-controls">{repositories.length===0?<p>Seçilebilir repo bulunamadı. Repo izinlerini yöneterek bir repo seçebilir, ardından listeyi yenileyebilirsiniz.</p>:<Field id="repository" label="GitHub reposu"><Select id="repository" value={selected} disabled={busy} onChange={event=>{setSelected(event.target.value);setPreview(undefined);setConfirmed(false);resetIssues();clearPrivateChoices(repositories.find(repo=>`${repo.installation_id}:${repo.id}`===event.target.value)?.private??false);}}><option value="">Bir repo seçin</option>{repositories.map(repo=><option key={`${repo.installation_id}:${repo.id}`} value={`${repo.installation_id}:${repo.id}`}>{repo.full_name} — {repo.private?'Gizli':'Açık'}</option>)}</Select></Field>}
 <Button variant="secondary" disabled={!selected||busy} onClick={()=>{if(lock.current)return;setPreview(undefined);setConfirmed(false);resetIssues();void perform(async()=>{const repo=repositories.find(item=>`${item.installation_id}:${item.id}`===selected);if(!repo)return;const data=await api<ProjectPreview>('projects/github/preview',{installation_id:repo.installation_id,repository_id:repo.id});setPreview(data);setRepoEditing(false);clearPrivateChoices(data.repository.private);if(!titleEdited.current)setTitle(data.repository.name);});}}>Paylaşımı hazırla</Button></div><p className="field-help">{repositoryCacheCaption(cachedAt)} · Listeyi gerektiğinde yenileyin.</p></>}
 </>}</>}</Surface>}
 {user&&config&&(existing||preview)&&<Surface className="project-editor-form"><form aria-busy={busy} onSubmit={event=>{event.preventDefault();if(!eligible||!taxonomySelected||!issueSelectionReady||(!id&&(!confirmed||!preview?.preview_token||!need||!mode||privateRepo&&(need==='bug'||mode==='pr'))))return;perform(async()=>{const listing={visibility,applications_open:applicationsOpen,...(['feature','bug'].includes(need)?{current_state:currentState,desired_outcome:desiredOutcome}:{})};const body=id?{title,category,subcategory,stage,description,...listing}:{title,category,subcategory,stage,description,...listing,need_type:need,participation_mode:mode,...(need==='bug'?(issueChoice==='new'?{create_issue:true}:{issue_number:Number(issueNumber)}):{}),preview_token:preview!.preview_token,installation_id:preview!.repository.installation_id,repository_id:preview!.repository.id,readme_excerpt:includeExcerpt?preview!.readme_excerpt:''};const data=await api<{project:Project}>(id?`projects/${id}`:'projects',body,id?'PATCH':'POST');router.push(`/projeler/${data.project.id}`);});}}><fieldset disabled={busy}><div className="project-editor-columns"><section className="project-editor-main" aria-labelledby="editor-project-heading"><h2 id="editor-project-heading">Proje ve katkı</h2>
 <Field id="project-title" label="Proje başlığı" error={fieldError('title')}><Input id="project-title" {...fieldA11y('title')} value={title} onChange={e=>{titleEdited.current=true;setTitle(e.target.value);setConfirmed(false);}} required maxLength={200}/></Field>
 <div className="project-editor-taxonomy"><Field id="project-category" label="Üst kategori" error={fieldError('category')}><Select id="project-category" {...fieldA11y('category')} value={selectedCategory?category:''} onChange={e=>{setCategory(e.target.value);setSubcategory('');setConfirmed(false);}} required disabled={!taxonomyReady}><option value="">Üst kategori seçin</option>{categories.map(item=><option key={item.value} value={item.value}>{item.label}</option>)}</Select></Field>
 <Field id="project-subcategory" label="Alt kategori" error={fieldError('subcategory')}><Select id="project-subcategory" {...fieldA11y('subcategory')} value={subcategories.some(item=>item.value===subcategory)?subcategory:''} onChange={e=>{setSubcategory(e.target.value);setConfirmed(false);}} required disabled={!taxonomyReady||!selectedCategory}><option value="">Alt kategori seçin</option>{subcategories.map(item=><option key={item.value} value={item.value}>{item.label}</option>)}</Select></Field>
 <Field id="project-stage" label="Proje durumu" help={selectedStage?.description} error={fieldError('stage')}><Select id="project-stage" {...fieldA11y('stage',!!selectedStage?.description)} value={selectedStage?stage:''} onChange={e=>{setStage(e.target.value);setConfirmed(false);}} required disabled={!taxonomyReady}><option value="">Proje durumu seçin</option>{stages.map(item=><option key={item.value} value={item.value}>{item.label}</option>)}</Select></Field>
 </div><Field id="project-need" label="Aranan katkı" help="Tek ihtiyaç seçin; yayımlandıktan sonra değişmez."><Select id="project-need" required disabled={!!id} value={need} onChange={e=>{setNeed(e.target.value);setConfirmed(false);resetIssues();}}><option value="">İhtiyaç seçin</option>{config.need_types?.filter(item=>item.value!=='bug'||!privateRepo).map(item=><option key={item.value} value={item.value}>{item.label}</option>)}</Select></Field>
 {['feature','bug'].includes(need)&&<div className="project-editor-outcomes"><Field id="project-current" label="Mevcut durum / sorun"><textarea className="input" id="project-current" required rows={3} maxLength={5000} value={currentState} onChange={e=>{setCurrentState(e.target.value);setConfirmed(false);}}/></Field><Field id="project-outcome" label="Beklenen sonuç"><textarea className="input" id="project-outcome" required rows={3} maxLength={5000} value={desiredOutcome} onChange={e=>{setDesiredOutcome(e.target.value);setConfirmed(false);}}/></Field></div>}
 {need==='bug'&&!id&&!privateRepo&&<><Field id="project-issue-choice" label="GitHub Issue"><Select id="project-issue-choice" value={issueChoice} onChange={e=>{issueRevision.current++;issueLock.current=false;setIssuesLoading(false);setIssuesError('');setIssueChoice(e.target.value);setIssueNumber('');setConfirmed(false);}}><option value="existing">Mevcut Issue’yu bağla</option><option value="new">Yeni Issue oluştur</option></Select></Field>{issueChoice==='existing'?<><p className="field-help">Yalnız bu public repodaki en yeni 50 açık Issue listelenir. Liste otomatik yüklenmez.</p><Button variant="secondary" loading={issuesLoading} disabled={busy||issuesLoading} onClick={()=>void loadIssues()}>{issueOptions===null?'Açık Issue’ları yükle':'Issue listesini yenile'}</Button>{issuesLoading&&<Alert role="status">Açık Issue’lar yükleniyor…</Alert>}{issuesError&&<Alert tone="error" role="alert">{issuesError} Issue listesini yeniden yükleyebilirsiniz.</Alert>}{issueOptions!==null&&!issuesLoading&&(issueOptions.length===0?<Alert role="status">Bu repoda listelenebilecek açık Issue bulunamadı. Yeni Issue oluşturmayı seçebilir veya listeyi yenileyebilirsiniz.</Alert>:<Field id="project-issue-number" label="Bağlanacak açık Issue" error={fieldError('issue_number')}><Select id="project-issue-number" required value={issueNumber} disabled={busy||issuesLoading} onChange={e=>{setIssueNumber(e.target.value);setConfirmed(false);}}><option value="">Bir Issue seçin</option>{issueOptions.map(issue=><option key={issue.number} value={String(issue.number)}>#{issue.number} — {issue.title}</option>)}</Select></Field>)}</>:<Alert>İlan başlığı, mevcut durum ve beklenen sonuçla GitHub reponuzda yeni Issue oluşturulacak.</Alert>}</>}

 <Field id="project-description" label="Açıklama (isteğe bağlı)" error={fieldError('description')}><textarea {...fieldA11y('description')} className="input project-textarea" id="project-description" value={description} onChange={e=>{setDescription(e.target.value);setConfirmed(false);}} maxLength={5000} rows={3}/></Field>
 </section><section className="project-editor-settings" aria-labelledby="editor-settings-heading"><h2 id="editor-settings-heading">Katılım ve yayın</h2><Field id="project-mode" label="Katılım yöntemi" help="İlan yayımlandıktan sonra değiştirilemez."><Select id="project-mode" required disabled={!!id} value={mode} onChange={e=>{setMode(e.target.value);setConfirmed(false);}}><option value="">Yöntem seçin</option>{config.participation_modes?.filter(item=>item.value!=='pr'||!(existing?.is_private??preview?.repository.private)).map(item=><option key={item.value} value={item.value}>{item.label}</option>)}</Select></Field>
 {mode==='automatic'&&<Alert><p>GitHub korumaları doğrulanmadan otomatik katılım açılamaz. Katılım, kullanıcının GitHub’da kabul edeceği yazma erişim daveti gönderir.</p><details className="project-editor-details"><summary>Gerekli GitHub korumaları</summary><p>Contributor adlı kısıtlı bir rol atanmaz. Mevcut bütün branch’ler ve bütün tag’ler GitHub ruleset kurallarıyla güncelleme, silme ve force-push işlemlerine karşı korunmalı, yalnız yöneticiler bu kuralları aşabilmelidir. Standart branch protection veya yalnız PR incelemesi şartı yeterli değildir. Katılımcı yeni bir çalışma branch’i açar. Ayarları GitHub’da tamamlayıp yeniden deneyin.</p></details></Alert>}
 <Field id="project-visibility" label="İlanı kimler görebilsin?"><Select id="project-visibility" value={visibility} onChange={e=>{setVisibility(e.target.value);setConfirmed(false);}}>{config.visibilities?.filter(item=>applicationsOpen||item.value!=='public').map(item=><option key={item.value} value={item.value}>{item.label}</option>)}</Select></Field>
 <Checkbox checked={applicationsOpen} onChange={e=>{setApplicationsOpen(e.target.checked);if(!e.target.checked&&visibility==='public')setVisibility('link');setConfirmed(false);}}>Başvurular açık</Checkbox>
 <p className="field-help">Kapalı ilanlar keşifte listelenmez. Yalnız seçilen kişilere görünür ilanlar davetle katılım alır.</p>

 {!id&&preview&&<><p className="field-help">{visibility==='public'?'İlan bilgileri herkese açık olarak keşifte yayımlanır.':visibility==='link'?'İlan bilgileri bağlantıya sahip herkes tarafından görülebilir; keşifte listelenmez.':'İlan bilgilerini yalnız sahibi, görüntüleme izni verilenler ve geçerli katılım daveti alanlar görebilir.'}</p>
 {preview.readme_excerpt?<><Checkbox checked={includeExcerpt} onChange={e=>{setIncludeExcerpt(e.target.checked);setConfirmed(false);}}>README özetini paylaş</Checkbox><details className="project-editor-details"><summary>README özetini incele</summary><p className="project-text">{preview.readme_excerpt}</p></details></>:<p className="field-help">Paylaşılabilecek README özeti bulunamadı.</p>}
 <details className="project-editor-details"><summary>Paylaşılacak bilgiler ve gizlilik</summary><p>{preview.repository.private?'Private repo bağlantısı, Issue ve PR verileri için ayrıca güncel GitHub erişimi gerekir. Açıklama ve README özetinde gizli bilgi olmadığını kontrol edin.':'Açık repo bağlantısı da paylaşılır.'} Onayladığınız bilgiler FIRST’te kaydedilir. GitHub’daki sonraki değişiklikler otomatik aktarılmaz. Görüntüleme izinleri ve katılım davetleri ilan detayından ayrı yönetilir.</p></details></>}
 </section></div><div className="project-editor-footer">{!id&&preview&&<div>{!preview.preview_token&&<Alert tone="error">Paylaşım hazırlığı güncel değil. Paylaşımı hazırla adımını yeniden deneyin.</Alert>}<Checkbox checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}>Gösterilen bilgileri gözden geçirdim ve seçtiğim görünürlük kapsamında paylaşılmasını onaylıyorum.</Checkbox></div>}

 <Button type="submit" loading={busy} disabled={!eligible||!taxonomySelected||!issueSelectionReady||(!id&&(!confirmed||!preview?.preview_token||!need||!mode||privateRepo&&(need==='bug'||mode==='pr')))}>{id?'Değişiklikleri kaydet':'Projeyi paylaş'}</Button></div></fieldset></form>
 {existing&&<Button variant={existing.is_active?'danger':'secondary'} disabled={busy||(!existing.is_active&&!eligible)} onClick={()=>perform(async()=>{const data=await api<{project:Project}>(`projects/${id}`,{is_active:!existing.is_active},'PATCH');setExisting(data.project);})}>{existing.is_active?'Paylaşımı arşivle':'Paylaşımı yeniden aç'}</Button>}
 </Surface>}</div>;
}
